const translations = {
    tr: {
        nav_manifesto: "Program",
        nav_curators: "Ekip",
        nav_project_brief: "Proje Briefi",
        nav_logbook: "Logbook",
        nav_exhibition: "Sergi",

        hero_badge: "Bahar Dönemi 2026 Pilot Programı",
        hero_title: "Yapay Zeka<br><span class=\"text-transparent border-text\">İle Tasarımı</span><br>Yeniden<br>Düşünmek.",
        hero_desc: "Özyeğin Üniversitesi Endüstriyel Tasarım Bölümü olarak, 2026 Bahar döneminde 1. sınıftan 4. sınıfa kadar tüm tasarım stüdyolarını kapsayan Dönüştürücü Eğitim Pilot Progamı'nı başlatmanın heyecanını yaşıyoruz.",
        hero_btn: "Sergiyi İncele",

        section_manifesto: "Program",
        seed_program_title: "Dönüştürü Eğitim Tohumlama Programı",
        seed_program_desc: "IDExAI.26, Özyeğin Üniversitesi Dönüştürücü Eğitim Tohumlama Programı kapsamında desteklenen bir eğitim girişimidir. Program, \"Yapay Zekâ ile Öğrenme\" teması doğrultusunda üniversitede yenilikçi öğrenme modellerinin geliştirilmesini teşvik etmektedir.",
        manifesto_h3: "IDExAI.26, üretken yapay zekânın tasarım sürecinin araştırma, fikir geliştirme, konsept oluşturma, prototipleme, test ve iletişim aşamalarına etkili ve sorumlu şekilde entegre edilmesini hedefleyen <span class=\"italic font-normal\">yeni bir eğitim modelidir.</span>",
        manifesto_p1: "Program, Beko eski Endüstriyel Tasarım İcra Direktörü Serdal Korkut Avcı’nın danışmanlığında; bölümümüzün öğretim üyeleri, stüdyo yürütücüleri ve araştırma ekibinin katkılarıyla yürütülmüştür.",
        manifesto_p2: "9 Şubat’taki başlangıç buluşmasının ardından, 12–16–17 Şubat tarihlerinde gerçekleştirilen hızlandırıcı ders (Crash Course) modülleri tamamlanmış; süreç, tüm sınıf seviyelerinin aynı tema üzerinde yapay zekâ destekli tasarım süreçleri geliştirdiği ortak stüdyo projesi ile tamamlanmıştır.",
        manifesto_quote: "\"Bu pilot program, yapay zekâyı yalnızca bir araç olarak değil, tasarım düşüncesinin aktif bir bileşeni olarak konumlandıran yeni bir tasarım eğitimi yaklaşımının ilk adımını temsil etmektedir.\"",
        framework_title: "Çerçevemiz",
        framework_copy: "Yapay Zekâ Destekli Tasarım Odaklı Düşünme: İnsan Odaklı İş Akışı",
        framework_roles_copy: "<strong>Yapay Zekâ Tartışma Partneri Rolleri</strong><p>IDExAI.26 kapsamında üretken yapay zekâ, tasarım sürecinde bir tasarım tartışma partneri olarak konumlandırılmıştır. Yapay zekâ; Clarifier, Reframer, Expander ve Critic gibi farklı roller üstlenerek tasarım problemini netleştirmeye, yeni bakış açıları geliştirmeye, alternatifler üretmeye ve fikirleri eleştirel biçimde değerlendirmeye yardımcı olur. Bu rol tabanlı yaklaşım, tasarım kararlarının sorumluluğunu tasarımcıda tutarken yapay zekâyı yapılandırılmış bir düşünme desteği olarak kullanmayı amaçlar.</p><div class=\"dt-roles-grid\"><div class=\"dt-role-card\"><strong>Netleştirici (Clarifier)</strong><br>Bilinmeyen içgörüleri ortaya çıkarır.</div><div class=\"dt-role-card\"><strong>Yeniden Çerçeveleyici (Reframer)</strong><br>Perspektifi değiştirir.</div><div class=\"dt-role-card\"><strong>Genişletici (Expander)</strong><br>Seçenekler üretir.</div><div class=\"dt-role-card\"><strong>Eleştirmen (Critic)</strong><br>Varsayımları sorgular.</div></div><strong>Tasarım Sorumluluğu Bildirimi</strong><div class=\"dt-responsibility-grid\"><div class=\"dt-responsibility-card\">Yapay zekâ olasılıklar üretir.</div><div class=\"dt-responsibility-card\">Tasarımcılar karar verir.</div><div class=\"dt-responsibility-card\">Tasarımcılar sorumluluğu taşır.</div></div>",
        dt_step_empathize: "Empati Kur",
        dt_step_define: "Tanımla",
        dt_step_ideate: "Fikir Geliştir",
        dt_step_prototype: "Prototiple",
        dt_step_test: "Test Et",
        dt_step_communicate: "İletişim Kur",
        dt_sub_empathize: "İnsanları ve bağlamı anla.<br>Sorular: Kullanıcı kim? Hangi davranışsal veya duygusal zorluk var?",
        dt_sub_define: "Doğru problemi çerçevele.<br>Sorular: Temel tasarım zorluğu nedir? Başarı neye benzer?",
        dt_sub_ideate: "Olasılıkları keşfet.<br>Sorular: Hangi farklı yönler var? Kısıtlar değişse ne olur?",
        dt_sub_prototype: "Fikirleri somutlaştır.<br>Sorular: Hangi varsayımı test ediyorsun? Deneyim nasıl simüle edilebilir?",
        dt_sub_test: "Geri bildirimle öğren.<br>Sorular: Ne işe yaradı? Neler başarısız oldu veya kullanıcıları şaşırttı?",
        dt_sub_communicate: "Düşünceni açıkla.<br>Sorular: Bu tasarım neden var? Kararları hangi kanıtlar destekliyor?",
        dt_step_empathize_aria: "Empati Kur adımı: Kullanıcıyı, bağlamı ve görünmeyen ihtiyaçları anlamlandırırız.",
        dt_step_define_aria: "Tanımla adımı: Problemi birlikte çerçeveler, tasarım odağını netleştiririz.",
        dt_step_ideate_aria: "Fikir Geliştir adımı: Farklı yönleri hızlıca üretir, seçenek havuzunu genişletiriz.",
        dt_step_prototype_aria: "Prototiple adımı: Fikirleri görünür kılmak için düşük riskli prototipler kurarız.",
        dt_step_test_aria: "Test Et adımı: Geribildirimle öğrenir, çözümü yeniden düzenleyip güçlendiririz.",
        dt_step_communicate_aria: "İletişim Kur adımı: Tasarım kararlarını açık ve kanıt temelli bir anlatıyla paylaşırız.",

        section_team: "Ekip",
        team_h3: "Stüdyo Yürütücüleri",
        section_project_brief: "Proje Briefi",
        project_brief_h3: "IDExAI.26 Proje Briefi",
        project_brief_desc: "<strong>2., 3. ve 4. Sınıflar – Sıcak İçecek Hazırlayan Elektronik Cihaz</strong><br>İkinci, üçüncü ve dördüncü sınıf öğrencileri, sıcak içecek hazırlamaya yönelik bir elektronik tezgâh üstü cihaz tasarladı. Proje; kullanıcı, kullanım senaryosu, etkileşim akışı, ergonomi, sistem mantığı ve teknik kurguyu birlikte ele almayı hedefledi. Öğrencilerden, mevcut ürünlere alternatif bir hazırlama deneyimi önermeleri ve yapay zekâyı fikir geliştirme, senaryo kurma, varyasyon üretme ve kararlarını değerlendirme süreçlerinde bilinçli biçimde kullanmaları beklendi.<br><br><strong>1. Sınıf – Yumurta Düşürme: Yapay Zekâ ile İş Birliği</strong><br>Birinci sınıf öğrencileri, hızlı bir tasarım görevi olarak yumurta düşürme (egg drop) çalışmasını gerçekleştirdi. Amaç, bir yumurtayı düşüşten koruyacak bir taşıyıcı/koruyucu sistem geliştirirken, yapay zekâ ile kurulan iş birliğini sorgulamaktı. Bu süreçte öğrenciler, fikir geliştirme, alternatif üretme, geri bildirim alma ve karar verme aşamalarında AI ile nasıl çalıştıklarını deneyimledi. Proje, yalnızca son ürüne değil, insan–yapay zekâ ortaklığının tasarım sürecine nasıl etki ettiğine odaklandı.",
        section_logbook: "Logbook",
        logbook_desc: "IDExAI.26 kapsamında öğrenciler tasarım süreçlerini Tasarımcının Seyir Defteri olarak adlandırılan logbook’larda kaydetti. Bu logbook’lar, öğrencilerin yapay zekâ ile kurdukları etkileşimleri, üretilen alternatifleri, yapılan seçimleri ve tasarımcı olarak verdikleri kararları görünür kılmayı amaçladı. Amaç yalnızca sonucu değil, düşünme sürecini, denemeleri ve tasarım muhakemesini belgelemekti. Program boyunca 100’den fazla öğrenci yüzlerce sayfayı bulan logbook’lar oluşturarak tasarım süreçlerini adım adım kayıt altına aldı. Aşağıda bazı logbook sayfalarından örnekleri görebilirsiniz.",

        section_collection: "Sergi",
        collection_h3: "Öğrenci<br>Projeleri",
        collection_desc: "Sergi iki projeye ayrılmıştır:<br>2-3-4. sınıflar için Sıcak İçecek Hazırlama Ürün Tasarımı,<br>1. sınıf için Yumurta Düşürme.",
        collection_btn_eggdrop: "Yumurta Düşürme Projesi Sergisine Git",
        collection_btn_hotbeverage: "Sıcak İçecek Hazırlama Ürün Tasarım Projesi Sergisine Git",
        eggdrop_title: "Yumurta Düşürme | 1. Sınıf Projesi",
        eggdrop_desc: "1. sınıf öğrencilerinin yumurta düşürme problemine odaklanan stüdyo çalışmaları.",
        hotbeverage_title: "Sıcak İçecek Hazırlayan Elektronik Cihaz | 2-3-4. Sınıf Projesi",
        hotbeverage_desc: "2, 3 ve 4. sınıf öğrencilerinin sıcak içecek hazırlama deneyimini elektronik ürün tasarımıyla yeniden ele aldığı proje koleksiyonu.",

        filter_all: "Tümü (100+)",
        filter_y1: "1. Sınıf",
        filter_y2: "2. Sınıf",
        filter_y3: "3. Sınıf",
        filter_y4: "4. Sınıf",
        hot_filter_all: "2-3-4 Tümü",
        global_filter_class: "Sınıf",
        student_search_placeholder: "Öğrenci adı",
        student_search_btn: "Ara",

        footer_dept: "Özyeğin Üniversitesi<br>Endüstriyel Tasarım Bölümü",
        footer_rights: "© 2026 Özyeğin Üniversitesi. Tüm Hakları Saklıdır.",

        modal_designer: "Tasarımcı",
        modal_process_h4: "Süreç & Metodoloji",
        modal_process_p: "Yapay zeka araçlarını tasarım sürecine nasıl entegre edildiğini özetleyen tasarım günlüğünü (logbook) özet sunumunu inceyebilirsiniz.",
        modal_logbook_btn: "Tasarım Adımlarını Görüntüle",
        modal_tools_h4: "Entegrasyon Araçları",

        card_examine: "İncele"
    },
    en: {
        nav_manifesto: "Program",
        nav_curators: "Team",
        nav_project_brief: "Project Brief",
        nav_logbook: "Logbook",
        nav_exhibition: "Exhibition",

        hero_badge: "Spring Semester 2026 Pilot Program",
        hero_title: "Designing<br><span class=\"text-transparent border-text\">With</span><br>Intelligence.",
        hero_desc: "As the Industrial Design Department at Özyeğin University, we are excited to launch the Transformative Education Pilot Program in Spring 2026, encompassing all design studio courses from Year 1 to Year 4.",
        hero_btn: "Explore Exhibition",

        section_manifesto: "Program",
        seed_program_title: "Transformative Education Seeding Program",
        seed_program_desc: "IDExAI.26 is an educational initiative supported under Özyeğin University’s Transformative Education Seeding Program. Aligned with the theme of \"Learning with Artificial Intelligence,\" the program encourages the development of innovative learning models across the university.",
        manifesto_h3: "IDExAI.26 is a new educational model that aims to integrate generative artificial intelligence effectively and responsibly into all stages of the design process, <span class=\"italic font-normal\">including research, ideation, concept development, prototyping, testing, and communication.</span>",
        manifesto_p1: "The program is conducted under the advisory of Serdal Korkut Avcı, former Executive Industrial Design Director at Beko, with the contributions of all studio instructors, faculty members, and the research team of our department.",
        manifesto_p2: "Following the kick-off meeting held on February 9, the intensive Crash Course modules conducted on February 12, 16, and 17 have been completed. The process continues with a shared studio project in which students across all class levels develop AI-supported design processes around a common theme.",
        manifesto_quote: "\"This pilot program represents the first step toward a new design education approach that positions artificial intelligence not merely as a tool, but as an active component of design thinking.\"",
        framework_title: "Our Framework",
        framework_copy: "AI-Supported Design Thinking: Human-Centered Workflow",
        framework_roles_copy: "<strong>AI Discussion Partner Roles</strong><p>Within IDExAI.26, generative AI is positioned as a design discussion partner in the design process. Through roles such as Clarifier, Reframer, Expander, and Critic, AI helps clarify problems, introduce new perspectives, generate alternatives, and critically evaluate ideas. This role-based approach supports structured thinking while keeping design decisions and responsibility in the hands of human designers.</p><div class=\"dt-roles-grid\"><div class=\"dt-role-card\"><strong>Clarifier</strong><br>Reveals unknown insights.</div><div class=\"dt-role-card\"><strong>Reframer</strong><br>Changes perspective.</div><div class=\"dt-role-card\"><strong>Expander</strong><br>Generates options.</div><div class=\"dt-role-card\"><strong>Critic</strong><br>Challenges assumptions.</div></div><strong>Design Responsibility Statement</strong><div class=\"dt-responsibility-grid\"><div class=\"dt-responsibility-card\">AI generates possibilities.</div><div class=\"dt-responsibility-card\">Designers make decisions.</div><div class=\"dt-responsibility-card\">Designers carry responsibility.</div></div>",
        dt_step_empathize: "Empathize",
        dt_step_define: "Define",
        dt_step_ideate: "Ideate",
        dt_step_prototype: "Prototype",
        dt_step_test: "Test",
        dt_step_communicate: "Communicate",
        dt_sub_empathize: "Understand people and context.<br>Questions: Who is the user? What behavior or emotional challenge exists?",
        dt_sub_define: "Frame the right problem.<br>Questions: What is the core design challenge? What does success look like?",
        dt_sub_ideate: "Explore possibilities.<br>Questions: What different directions exist? What if constraints changed?",
        dt_sub_prototype: "Make ideas tangible.<br>Questions: What assumption are you testing? How can the experience be simulated?",
        dt_sub_test: "Learn through feedback.<br>Questions: What worked? What failed or surprised users?",
        dt_sub_communicate: "Explain your thinking.<br>Questions: Why does this design exist? What evidence supports decisions?",
        dt_step_empathize_aria: "Empathize step: We study users, context, and unmet needs before deciding direction.",
        dt_step_define_aria: "Define step: We frame the core challenge and align the design focus.",
        dt_step_ideate_aria: "Ideate step: We generate and compare many possible solution directions.",
        dt_step_prototype_aria: "Prototype step: We build quick artifacts to make ideas discussable and testable.",
        dt_step_test_aria: "Test step: We learn from feedback and refine the solution iteratively.",
        dt_step_communicate_aria: "Communicate step: We explain design decisions through a clear, evidence-based narrative.",

        section_team: "Team",
        team_h3: "Studio Instructors",
        section_project_brief: "Project Brief",
        project_brief_h3: "IDExAI.26 Project Brief",
        project_brief_desc: "<strong>Years 2, 3, and 4 – Hot Beverage Preparing Electronic Device</strong><br>Second-, third-, and fourth-year students worked on designing a countertop electronic device for preparing hot beverages. The project asked students to define a user, build a clear use scenario, and develop a concept through form, interaction, ergonomics, and system logic. Students were expected to propose an alternative preparation experience while using AI consciously as a partner in concept exploration, scenario generation, variation, and decision-making.<br><br><strong>Year 1 – Egg Drop: Partnering with AI</strong><br>As a quick design challenge, first-year students completed an Egg Drop project. The aim was to design and build a protective system for an egg while reflecting on what it means to collaborate with AI during the design process. Students explored how AI could support ideation, iteration, feedback, and decision-making. Rather than focusing only on the final outcome, the project emphasized the experience of partnering with AI in design.",
        section_logbook: "Logbook",
        logbook_desc: "As part of IDExAI.26, students documented their design processes in Design Logbooks. These logbooks record interactions with AI tools, generated alternatives, design decisions, and the contributions made by the designer throughout the process. The goal was not only to document the final outcome, but to make design thinking, iterations, and decision-making visible. Throughout the program, more than 100 students collectively produced hundreds of pages of logbooks, capturing their design journeys step by step. Below you can see selected pages from these logbooks.",

        section_collection: "Exhibition",
        collection_h3: "Student<br>Projects",
        collection_desc: "The exhibition is split into two tracks:<br>Hot Beverage Preparing Electronic Device for Years 2, 3, and 4,<br>and Egg Drop for Year 1.",
        collection_btn_eggdrop: "Go to Egg Drop Project Exhibition",
        collection_btn_hotbeverage: "Go to Hot Beverage Preparing Product Design Exhibition",
        eggdrop_title: "Egg Drop | Year 1 Project",
        eggdrop_desc: "Year 1 studio outcomes focused on the egg drop challenge.",
        hotbeverage_title: "Hot Beverage Preparing Electronic Device | Year 2-3-4 Project",
        hotbeverage_desc: "The project collection where Years 2, 3, and 4 reinterpret hot beverage preparation through electronic product design.",

        filter_all: "All (100+)",
        filter_y1: "Year 1",
        filter_y2: "Year 2",
        filter_y3: "Year 3",
        filter_y4: "Year 4",
        hot_filter_all: "All 2-3-4",
        global_filter_class: "Class",
        student_search_placeholder: "Student name",
        student_search_btn: "Search",

        footer_dept: "Özyeğin University<br>Industrial Design Department",
        footer_rights: "© 2026 Özyeğin University. All Rights Reserved.",

        modal_designer: "Designer",
        modal_process_h4: "Process & Methodology",
        modal_process_p: "Explore the design logbook summary presentation, which summarizes how AI tools were integrated into the design process.",
        modal_logbook_btn: "View Design Milestones",
        modal_tools_h4: "Integration Tools",

        card_examine: "Examine"
    }
};

const instructors = [
    { name: { tr: "PROF. DR. ALPAY ER", en: "PROF. DR. ALPAY ER" }, role: { tr: "ENDÜSTRİYEL TASARIM BÖLÜM BAŞKANI", en: "Head of Industrial Design Department" }, image: "assets/instructors/alpay_er.png" },
    { name: { tr: "SERDAL KORKUT AVCI", en: "SERDAL KORKUT AVCI" }, role: { tr: "PROJE DANIŞMANI VE KOORDİNATÖRÜ, YARI ZAMANLI ÖĞR. GÖR.", en: "Project Advisor & Coordinator, Part-time Instructor" }, image: "assets/instructors/korkut_avci.png" },
    { name: { tr: "ARŞ. GÖR. ULAŞ TİGİN", en: "RES. ASST. ULAŞ TİGİN" }, role: { tr: "PROJE KOORDİNATÖRÜ", en: "Project Coordinator" }, image: "assets/instructors/ulas_tigin.png" },
    { name: { tr: "PROF. DR. ŞEBNEM TİMUR", en: "PROF. DR. ŞEBNEM TİMUR" }, role: { tr: "STÜDYO DERS YÜRÜTÜCÜSÜ", en: "Studio Instructor" }, image: "assets/instructors/sebnem_timur.png" },
    { name: { tr: "DR. ÖĞR. ÜYESİ ZEYNEP KARAPARS", en: "ASST. PROF. DR. ZEYNEP KARAPARS" }, role: { tr: "STÜDYO DERS YÜRÜTÜCÜSÜ", en: "Studio Instructor" }, image: "assets/instructors/zeynep_karapars.png" },
    { name: { tr: "ÖĞR. GÖR. DR. EMRAH ÖZTURAN", en: "INST. DR. EMRAH ÖZTURAN" }, role: { tr: "STÜDYO DERS YÜRÜTÜCÜSÜ", en: "Studio Instructor" }, image: "assets/instructors/emrah_ozturan.png" },
    { name: { tr: "ÖĞR. GÖR. ALİ GÖKKURT", en: "INST. ALİ GÖKKURT" }, role: { tr: "STÜDYO DERS YÜRÜTÜCÜSÜ", en: "Studio Instructor" }, image: "assets/instructors/ali_gokkurt.png" },
    { name: { tr: "ÖĞR. GÖR. TUĞBA TOK", en: "INST. TUĞBA TOK" }, role: { tr: "STÜDYO DERS YÜRÜTÜCÜSÜ", en: "Studio Instructor" }, image: "assets/instructors/tugba_tok.png" },
    { name: { tr: "ARŞ. GÖR. DR. PELİN GÜNAY", en: "RES. ASST. DR. PELİN GÜNAY" }, role: { tr: "STÜDYO DERS YÜRÜTÜCÜSÜ", en: "Studio Instructor" }, image: "assets/instructors/pelin_gunay.png" },
    { name: { tr: "AYSU DERİCİOĞLU EGEMEN", en: "AYSU DERİCİOĞLU EGEMEN" }, role: { tr: "YARI ZAMANLI ÖĞRETİM GÖREVLİSİ", en: "Part-time Instructor" }, image: "assets/instructors/aysu_dericioglu.png" },
    { name: { tr: "GAMZE GÜVEN", en: "GAMZE GÜVEN" }, role: { tr: "YARI ZAMANLI ÖĞRETİM GÖREVLİSİ", en: "Part-time Instructor" }, image: "assets/instructors/gamze_guven.png" },
    { name: { tr: "SEYMAN ÇAY", en: "SEYMAN ÇAY" }, role: { tr: "YARI ZAMANLI ÖĞRETİM GÖREVLİSİ", en: "Part-time Instructor" }, image: "assets/instructors/seyman_cay.png" },
    { name: { tr: "SONAY ARDİ AKKAR", en: "SONAY ARDİ AKKAR" }, role: { tr: "YARI ZAMANLI ÖĞRETİM GÖREVLİSİ", en: "Part-time Instructor" }, image: "assets/instructors/sonay_ardi.png" },
    { name: { tr: "EDA SARMAN", en: "EDA SARMAN" }, role: { tr: "ÖĞRETİM ASİSTANI", en: "Teaching Assistant" }, image: "assets/instructors/eda_sarman.png" },
    { name: { tr: "ELİF DOĞRUL", en: "ELİF DOĞRUL" }, role: { tr: "ÖĞRETİM ASİSTANI", en: "Teaching Assistant" }, image: "assets/instructors/elif_dogrul.png" },
    { name: { tr: "HALİL BORAN", en: "HALİL BORAN" }, role: { tr: "ÖĞRETİM ASİSTANI", en: "Teaching Assistant" }, image: "assets/instructors/halil_boran.png" }
];

// CSV metnini (header dahil) bu template string'in icine direkt yapistirabilirsin.
const projectsCsv = `id,first_name,last_name,year,title_tr,short_desc_tr,title_en,short_desc_en,tools,image,pdf
1,Beste,Yılmaz,1,Çekirdek Koruma,CoreGuard; merkezdeki çekirdeği — yani yumurtayı — 3 metrelik bir düşüşten korumak için tasarlanmış hafif bir yapıdır. Üçgen bir iç çerçeve yumurtayı merkezde tutarken; dışa doğru uzanan radyal pipetler darbe kuvvetini emerek dağıtır. Tasarım; sınırlı malzemeler içinde denge; simetri ve enerji dağılımını sağlamaya odaklanır.,Coreguard,CoreGuard is a lightweight structure designed to protect a central core — the egg — from a 3-meter drop. A triangular inner frame holds the egg while radial outer straws absorb and spread the impact force. The design focuses on balancing stability; symmetry; and energy distribution within strict material limits.,ChatGPT;Gemini,cover/01.jpg,logbook/01.pdf
2,Doğa,Çoknaz,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/02.jpg,logbook/02.pdf
3,Ece,Gündoğan,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/03.jpg,logbook/03.pdf
4,Efe,Gülan,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/04.jpg,logbook/04.pdf
5,İpek,Turgay,1,Operasyon: Yumurtayı Kurtar,Bu proje; bir yumurtayı düşme sırasında koruyabilecek bir yapı tasarlamayı amaçlamaktadır. İlk aşamada farklı pipet yapıları denenerek yapısal davranış gözlemlenmiştir. İkinci aşamada ise daha sınırlı malzemelerle; AI desteği kullanılarak daha verimli bir yapı tasarımı geliştirilmeye çalışılmıştır.,Operation: save the egg,This project aims to design a structure that can protect an egg during a fall. In the first stage; different straw structures were tested to observe structural behavior. In the second stage; a more efficient design was developed using limited materials and AI support.,ChatGPT,cover/05.jpg,logbook/05.pdf
6,Isık,Günal,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/06.jpg,logbook/06.pdf
7,Miray,Yılmaz,1,Sivri Koruma,Bu proje; Egg Drop Challenge’da yapısal dayanıklılığı değerlendirir. İlk tasarım; kinetik enerjiyi dağıtmak için yoğun ve esnek bir pipet ağı kullanarak başarılı oldu. İkinci tasarım ise minimalist ve sert üçgen bir çerçeveydi; ancak iç süspansiyonu olmadığı için darbeyi absorbe edemedi ve başarısız oldu.,spike guard,This project evaluates structural resilience in an Egg Drop Challenge. The first design used a dense; flexible straw network to dissipate kinetic energy and was successful. The second design used a rigid triangular frame but failed because it lacked internal suspension to absorb the impact.,ChatGPT; Gemini,cover/07.jpg,logbook/07.pdf
8,Nehir,Günaçtı,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/08.jpg,logbook/08.pdf
9,Nehir,Öztürk,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/09.jpg,logbook/09.pdf
10,Nihal,Cankaya,1,Güvenli Düşüş,Bu proje; basit malzemeler kullanarak bir yumurtayı darbeden koruyan bir yapı tasarlamayı; deneme-yanılma; tasarım tekrarları ve süreç boyunca AI’dan alınan destek ile geliştirmeyi amaçlamaktadır.,The Safe Fall,This project explores the design of a structure that protects an egg from impact using simple materials ; developed through experimentation; iteration; and support from AI during the design process.,ChatGPT,cover/010.jpg,logbook/010.pdf
11,Nisa,Yıldız,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/011.jpg,logbook/011.pdf
12,Selin,Kanberoğlu,1,Yumurta Kalkanı,,Egg shield,,,cover/012.jpg,logbook/012.pdf
13,Sinem,Menteşeoğlu,1,Koruyucu Yumurta Kabuğu,Bu proje gündelik malzemelerden; yumurtayı 3 metrelik düşüşten koruyacak bir tasarım yapmaktır. İlhamım mars sondalarının inişleri için kullanılan sistemden gelmiştir. Esnek dış kabuk zıplama sağlarken; sağlam iç kabuk içindeki objeyi sıkı bir şekilde tutup yere değip hasar görmesinden korur. Bu projenin amacı tasarım sürecinde yapay zekanın nasıl bir yer edindiğini görmek ve onu avantajımıza çevirmektir.,Protective Egg Shell,This project aims to create a design to protect an egg from a 3-meter fall using everyday materials. My inspiration comes from the system used for landing Mars probes. The flexible outer shell provides bounce; while the sturdy inner shell firmly holds the object inside; protecting it from damage upon impact with the ground. The goal of this project is to see how AI plays a role in the design process and how we can turn it to our advantage.,ChatGPT; Gemini,cover/013.jpg,logbook/013.pdf
14,Yağmur,Cimsit,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/014.jpg,logbook/014.pdf
15,Begüm,Hacıcaferoğlu,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/015.jpg,logbook/015.pdf
16,Berk,Bahadır,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/016.jpg,logbook/016.pdf
17,Beste,Erbilgin,1,AltıgenYuva,sınırlı malzemelerle yumurtayı 3 metreden düştüğünde koruyacak koruma yaptık,HexaNest,Using limited materials; we created a shield that will protect an egg when it falls from 3 meters.,ChatGBT Gemini,cover/017.jpg,logbook/017.pdf
18,Ceylin,Göksu,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/018.jpg,logbook/018.pdf
19,Cinarhan,Çatal,1,Pipet Kalkanı,,StrawGuard,,,cover/019.jpg,logbook/019.pdf
20,Defne,İnci,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/020.jpg,logbook/020.pdf
21,Deniz,Yurdakul,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/021.jpg,logbook/021.pdf
22,Didem,Yüksek,1,Yumurta Kırılma Önleme,Sınırlı sayıda malzeme kullanarak; 3 metre yükseklikten atılıp yere çarptığında da içindeki yumurtayı koruyacak bir sistem geliştirdik.,Egg Breakage Prevention,Using a limited number of materials; we developed a system that will protect the egg inside even when it is dropped from a height of 3 meters and hits the ground.,ChatGPT; Gemini,cover/022.jpg,logbook/022.pdf
23,Duru,Köseoğlu,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/023.jpg,logbook/023.pdf
24,İrem,Seniceli,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/024.jpg,logbook/024.pdf
25,Kaan,Korun,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/025.jpg,logbook/025.pdf
26,Kaan,Olcar,1,Yumuşak İniş,Bu tasarım; yumurtayı hafif bir üçgen çerçevenin içinde askıda tutarak korur. Dış yapı; iniş sırasında oluşan darbe kuvvetlerini emen ve dağıtan koruyucu bir kafes görevi görür. Yapı yere çarptığında; şokun büyük kısmını dış çerçeve karşılar ve iç kısım yumurtayı doğrudan temas ve darbeden izole eder. Üçgen form aynı zamanda düşüş sırasında yapının daha dengeli kalmasına yardımcı olur. Darbenin gerçekleştiği bölge ile kırılgan nesneyi birbirinden ayırarak bu tasarım; yumurtanın düşüşten sağ çıkma ihtimalini artırır.,A Gentle Landing,This design protects the egg by suspending it inside a lightweight triangular frame. The outer structure acts as a protective cage that absorbs and distributes impact forces during landing. When the structure hits the ground; the external frame takes most of the shock while the inner core keeps the egg isolated from direct contact. The triangular form also helps stabilize the structure during the fall. By separating the impact zone from the fragile object; the design increases the chances of the egg surviving the drop.,ChatGPT; Gemini,cover/026.jpg,logbook/026.pdf
27,Kibunja,Maina,1,Yumurta Düşür,,Egg Drop,This design protects the egg by suspending it inside a lightweight triangular frame. The outer structure acts as aprotective cage that absorbs and distributes impact forces during landing. When the structure hits the ground; theexternal frame takes most of the shock while the inner core keeps the egg isolated from direct contact. The triangular form also helps stabilize the structure during the fall. By separating the impact zone from the fragile object; the designincreases the chances of the egg surviving the drop.,ChatGPT; Gemini; Vizcom,cover/027.jpg,logbook/027.pdf
28,Naz,Bektaş,1,Yumurta Düşür,,Egg Drop,This design protects the egg by suspending it inside a lightweight triangular frame. The outer structure acts as a protective cage that absorbs and distributes impact forces during landing. When the structure hits the ground; the external frame takes most of the shock while the inner core keeps the egg isolated from direct contact. The triangular form also helps stabilize the structure during the fall. By separating the impact zone from the fragile object; the design increases the chances of the egg surviving the drop.,ChatGPT; Gemini,cover/028.jpg,logbook/028.pdf
29,Nehir,Karavaş,1,Yumurta Düşür,,Egg Drop,This design protects the egg by suspending it inside a lightweight triangular frame. The outer structure acts as a protective cage that absorbs and distributes impact forces during landing. When the structure hits the ground; the external frame takes most of the shock while the inner core keeps the egg isolated from direct contact. The triangular form also helps stabilize the structure during the fall. By separating the impact zone from the fragile object; the design increases the chances of the egg surviving the drop.,ChatGPT; Gemini,cover/029.jpg,logbook/029.pdf
30,Nil,Gökberk,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/030.jpg,logbook/030.pdf
31,Nilsu,Durna,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/031.jpg,logbook/031.pdf
32,Nurefsan,Kangal,1,Yumurta Düşür,,Egg Drop,,ChatGPT;Gemini,cover/032.jpg,logbook/032.pdf
33,Zeynep,Baş,1,Yumurta Dengede,Bu proje; pipet ve ip kullanarak darbe kuvvetini dağıtan ve düşme sırasında kırılgan bir yumurtayı koruyan geometrik bir yapı tasarlamayı amaçlar.,Egg in Balance,This project uses straws and string to create a geometric structure that distributes impact and protects a fragile egg during a drop.,ChatGPT; Gemini,cover/033.jpg,logbook/033.pdf
34,Zeynep,Özkan,1,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini,cover/034.jpg,logbook/034.pdf
35,Ceren,Afacan,2,Çocuklar için sıcak çikolata makinesi,Çocukların aile kahve ritüellerine katılması ve bireysel ritüel geliştirmeleri için sıcak çikolata makinesi,Hot chocolate maker for kids,A hot chocolate machine for children to participate in family coffee rituals and develop their own individual rituals.,ChatGPT; Gemini; Vizcom,cover/035.jpg,logbook/035.pdf
36,Defne,Sevimay,2,Bitki Çayı Hazırlama Makinesi,Kullanıcının sağlık ihtiyaçlarına göre bitki karışımlarını hazırlayan;dozlayan akıllı çay makinesi,Herbal Tea Preperation Machine,A smart tea machine that prepares and doses herbal blends according to the user’s health needs.,ChatGPT; Gemini; Vizcom,cover/036.jpg,logbook/036.pdf
37,Demir,Yapar,2,Temizlik durumu izlenebilir kapsül kahve makinesi,Kapsül kahve makinesi,Capsule coffee machine,Shows hygiene status,ChatGPT,cover/037.jpg,logbook/037.pdf
38,Ela,Saçak,2,Kamara İçi Premium Botanik Demleme İstasyonu,Lüks cruise kamaraları için tasarlanan; filtre kahve makinesi mantığıyla çalışan analog bir bitki çayı demleme istasyonudur. Dijital arayüzlerden arındırılmış bu sistem; kullanıcının paslanmaz çelik süzgece taze bitkiler ekleyerek kendi çayını hazırladığı atıksız bir ritüel sunar. Duvara monte yapısı ve sarsıntıya dayanıklı; sızdırmaz (dual-lid) dikey termosu ile deniz şartlarında güvenli ve estetik bir çözüm sağlar.,The Beacon Hub: In-Cabin Premium Botanical Brewer,Designed for luxury cruise cabins; this analog botanical tea brewer operates on a simple drip-infusion mechanism. Stripped of digital screens; it offers a zero-waste wellness ritual using fresh herbs and a stainless steel basket. Its wall-mounted design and spill-proof; vertical-lift thermos ensure a safe; elegant; and motion-resistant beverage experience at sea.,ChatGPT; Gemini; Vizcom,cover/038.jpg,logbook/038.pdf
39,Ilgın,Boyraz,2,Taşınabilir Akıllı Termos,Kullanıcıların çay; kahve; meyve çayı veya instant çorba gibi sıcak içecekleri ve hafif karışımları istedikleri yerde hazırlayabilmelerini sağlayan taşınabilir akıllı termos cihazıdır. Ürün içinde bulunan ısıtma ve karıştırma mekanizması sayesinde içerikler termos içinde hazırlanabilir.,Smart Portable Thermos ,A portable smart thermos that allows users to prepare tea; coffee; fruit-infused tea; or instant soup anywhere. The device includes a built-in heating and mixing system that helps ingredients brew and blend directly inside the thermos.,ChatGPT; Gemini; Vizcom,cover/039.jpg,logbook/039.pdf
40,Yağmur,Bekki,2,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/040.jpg,logbook/040.pdf
41,Yağmur,Vidin,2,Taşınabilir Kendi Kendine Kahve Demleyen Termos,Kullanıcıların istedikleri yerde taze kahve hazırlayabilmesi için tasarlanmış taşınabilir bir kahve demleme termosudur. Dahili ısıtıcı; su tankı ve filtreli kahve haznesi sayesinde kahveyi cihaz içinde demleyip doğrudan içmeye olanak sağlar.,Portable Self-Brewing Coffee Thermos,A portable coffee brewing thermos. It includes a built-in heater and filter system that allows users to prepare coffee inside the device and drink it directly.,ChatGPT; Gemini; Vizcom,cover/041.jpg,logbook/041.pdf
42,Zeynep,Karadoğan,2,Akıllı Hijyen Kettle’ı,Akıllı Hijyen Kettle’ı; yurt mutfakları gibi ortak kullanım alanlarında hijyen durumunu görünür kılarak kullanıcılar arasında güven oluşturmayı amaçlayan; demleme hazneli ve mobil uygulama destekli bir sıcak içecek hazırlama cihazıdır.,Smart Hygiene Kettle,Smart Hygiene Kettle is a hot beverage appliance designed for shared environments such as dorm kitchens; aiming to build trust between users by making hygiene status visible; while supporting tea brewing through an integrated infuser and a mobile application.,ChatGPT; Gemini; Tripo AI,cover/042.jpg,logbook/042.pdf
43,Alara,Bayrak,2,Taşınabilir filtre kahve makinesi,Isıtma haznesi; filtreleme haznesi; termos gövdesi ve kahve saklama bölmesinden oluşan dört modüllü taşınabilir elektrikli filtre kahve makinesi.,Portable Filter Coffee Machine,A portable electric filter coffee machine that consists of four modules: a heating chamber; filtering chamber; thermos body and a coffee storage compartment.,ChatGPT 5.3; Gemini; Vizcom,cover/043.jpg,logbook/043.pdf
44,Bengi,Baki,2,Matcha Hazırlama Makinesi,Son tasarım yönü; modern şehirli kullanıcılar ve yoğun çalışan genç profesyoneller için; geleneksel matcha hazırlama ritüelini otomatikleştiren ve minimum kullanıcı çabasıyla zahmetsiz bir deneyim sunan; tek aksiyonlu ve kesintisiz bir matcha makinesi tasarlamaktır.,Matcha Preparing Device.,The final design direction is to create a seamless; single-action matcha maker for modern urban users and young busy professionals; automating the traditional ritual and delivering a zero-hassle experience with minimal user effort.,ChatGPT; Gemini; Vizcom,cover/044.jpg,logbook/044.pdf
45,Berra,Ulusoy,2,Akıllı Çocuk Süt Isıtıcısı,Çocukların sütlerini doğru sıcaklık ve pratik biçimde hazırlar.,Smart Toddler Milk Warmer,Ensures safe milk temperature for babies.,ChatGPT; Gemini; Vizcom,cover/045.jpg,logbook/045.pdf
46,Doğa,Şahin,2,Çay Kültürünü Destekleyen Taşınabilir Çoklu Çay Demleme Sistemi,Farklı çay türlerinin doğru sıcaklık ve hazırlama yöntemleriyle hazırlanmasını destekleyen taşınabilir bir çay demleme sistemi. Sistem; çayın mutfakta hazırlanıp farklı yaşam alanlarında tüketebilmesini sağlayarak çay kültürünü destekler.,Portable Multi-Tea Brewing System for Tea Culture,A portable tea brewing system designed to support different tea varieties with their correct brewing conditions. The system allows tea to be prepared in the kitchen and enjoyed in different living spaces while supporting tea culture.,ChatGPT; Gemini,cover/046.jpg,logbook/046.pdf
47,Duru,Ege,2,Ritüel odaklı bitki çayı hazırlama ünitesi,Evden çalıştığı için sürekli bilgisayar ve teknoloji ile iç içe olan kişilere bu teknolojiden uzaklaşıp kontrolün kendilerinde olduğunu ve anda hissedebildikleri analog bir deneyim sağlayan bir makine,Ritual-Based Herbal Tea Preparation System,A device that provides an analog experience for home-working individuals who are constantly exposed to technology; allowing them to disconnect from digital systems and regain a sense of control and presence.”,ChatGPT; Gemini; Vizcom,cover/047.jpg,logbook/047.pdf
48,Ece,Baki,2,Şerbet makinesi,Şerbeti otomatik olarak demleyen ve servis eden modern bir şerbet hazırlama makinesi.,Sherbet Machine,A modern sherbet making machine that automatically brews and serves sherbet.,ChatGPT; Gemini; Vizcom,cover/048.jpg,logbook/048.pdf
49,Emre,Bediroğlu,2,Vakumlu Bitki Çayı Makinesi,Tekne;Bot;Kayık gibi ortamlarda devrilmeyen vakumlu bitki çayı hazırlayan termos kettle,Vacuum Herbal Tea Kettle-Thermos,A vacuum-sealed thermos kettle that prepares herbal tea without tipping over in environments such as boats; dinghies; and kayaks.,ChatGPT; Gemini; Vizcom,cover/049.jpg,logbook/049.pdf
50,Eren,Göksu,2,Otomatik Kahve Makinesi,Yaşlılar ve motor beceri sorunları yaşayan bireyler için kahve Makinesi,Automatic Coffee Machine,A coffe machine for elderly and people with motor impairments.,ChatGPT; Claude; Vizcom,cover/050.jpg,logbook/050.pdf
51,Esma,Özbey,2,Ev Coffee Corner’ları İçin Çok Fonksiyonlu Espresso Makinesi,Coffee corner’lar için tasarlanmış kompakt bir espresso makinesi; kahve öğütme; espresso hazırlama ve süt köpürtme işlevlerini tek üründe sunar.,A Multifunctional Espresso Machine for Home Coffee Corners,A compact espresso machine designed for coffee corners that combines coffee grinding; espresso brewing; and milk frothing in a single product.,ChatGPT; Gemini; Vizcom,cover/051.jpg,logbook/051.pdf
52,Esra,Eksik,2,Yöresel Kahve Çeşitleri Hazırlayabilen Otomatik Kahve Makinesi,Türk; Dibek; Menengiç ve Süryani olmak üzere dört farklı yöresel kahve çeşidini hazırlayabilen bu kahve makinesi; yumuşak; orta ve sert içim seçenekleri sunar. İstenilen içime göre dozajlamayı otomatik olarak ayarlayarak kahveyi kolay ve usulüne uygun şekilde pişirir.,Automatic Coffee Machine That Can Prepare Regional Coffee Varieties.,This coffee machine can prepare four different regional coffee varieties: Turkish; Dibek; Menengiç; and Süryani; offering mild; medium; and strong brewing options. It automatically adjusts the dosage according to your desired brewing style; making it easy and proper to prepare your coffee.,ChatGPT; Gemini; Vizcom,cover/052.jpg,logbook/052.pdf
53,Gülce,Gez,2,Karavanda Kullanıma Yönelik Kahve Makinesi,Kendi kahvesini öğütebilen; güneş enerjisini ikincil bir enerji kaynağı olarak kullanan; hem masa üstünde hem de elde kullanılabilir kahve makinesi.,Coffee Machine for Caravan,A coffee machine that can grind its own coffee; uses solar energy as a secondary energy source; and can be used both on a tabletop and by hand.,ChatGPT; Gemini; Vizcom; Claude,cover/053.jpg,logbook/053.pdf
54,İlayda,Ünaldi,2,Gemindeki mürettebat için filtre kahve makinası,Şehirlerarası ve şehirleriçi gemilerde çalışan insanlar için  filtre kahve makinası tasarlamak istedim. Sağlamlık; denge; dökülme riskini azlatma gibi önceliklerim vardı.,Filter coffee machine for the ship crews,“I will design for ship crews working in small and unstable sea environments by focusing on the risk of electrical shocks and spilling liquids because it causes dangerous accidents and creates stress.”,ChatGPT; Gemini,cover/054.jpg,logbook/054.pdf
55,İpek,Üstün,2,Yatak Odası İçin Bitkisel Çay  Makinesi,Akşamleyin bitkisel çay içmeyi seven ve bunu gece rutinlerinin bir parçası haline getiren insanlar için odalarında bulundurabilecekleri su kaynatıp bitkisel çay demleyen bir makine,Herbal Tea Brewer for the Bedroom,A herbal tea brewer for people who like drinking herbal tea  and make herbal tea drinking a part of their nightly routine,ChatGPT; Gemini; Vizcom,cover/055.jpg,logbook/055.pdf
56,Lara,Karasal,2,Salep Yapma ve Isıtma Makinesi,Yerel ve yurt dışına açılmış olan kahve zincirleri için hem yapıp hem de sıcak tutan bir makine olarak servisi hızlandıran ve salep kültürünü yaymak amacıyla tasarlanmış makinedir.,Salep Preparation Machine,This project explores the design of a compact machine that can both prepare and heat salep in a single system. Current salep machines are mostly used only for keeping the beverage warm; while the preparation process still requires a separate stove. By integrating preparation and heating into one machine; the design aims to simplify the service process in coffee chains and make salep more accessible in modern beverage culture.,ChatGPT; Gemini,cover/056.jpg,logbook/056.pdf
57,Nehir,Aslan,2,Otel Odalarında Türk Çayı Deneyimi,Otel odalarında turistlere Türk çayı ritüelini ve semaver kültürünü öğretmeyi ve deneyimletmeyi hedefleyen kompakt bir çay makinesi.,Turkish Tea Experience in Hotel Rooms,A compact tea machine designed to teach and allow tourists to experience the Turkish tea ritual and samovar culture in hotel rooms.,ChatGPT; Gemini,cover/057.jpg,logbook/057.pdf
58,Özlem,Akgül,2,Ofis İçin Filtre Kahve Makinesi,Ortak kullanılan ofislerde küf ve kötü koku oluşumunu engelleyen; temizliği ön planda tutan kolay kullanımlı filtre kahve makinesi.,Filter Coffee Machine for the Office,An easy to use filter coffee machine that prevents mold and unpleasant odors in shared office spaces; prioritizing cleanliness.,ChatGPT; Gemini; Vizcom,cover/058.jpg,logbook/058.pdf
59,Sedef,Aydın,2,Manuel Kahve Öğütücü ve Demleyici,Bu proje; manuel kahve öğütme ve demlemeyi tek bir cihazda birleştiren bir espresso makinesi konseptidir. Kullanıcılar; basınç ve sıcaklığı kontrol ederek İtalyan kahvesi hazırlama ritüelini yaşayabilir.,Manual Coffee Grinder & Brewer,This project is a concept for an espresso machine that combines manual coffee grinding and brewing in a single device. Users can control pressure and temperature while experiencing the ritual of preparing Italian coffee.,ChatGPT; Gemini; Vizcom,cover/059.jpg,logbook/059.pdf
60,Şevval,Boydak,2,Yönlendirmeli Bitki Çayı Demleme Cihazı,Ev kullanımı için tasarlanmış; bilgi kirliliği ve bilgi fazlalığı nedeniyle bunalmış kullanıcıların yönlendirilmiş tarifler ve basit bir arayüz aracılığıyla sağlıklı bitki çayı demlemelerine yardımcı olan bir makine.,Guided Herbal Infusion Brewer,A home herbal tea brewing machine that helps overwhelmed users prepare healthy infusions through guided recipes and a simple interface.,ChatGPT; Gemini; Vizcom,cover/060.jpg,logbook/060.pdf
61,Sude,Alsan,2,Ofisler ve Paylaşımlı alanlar için kahve makinesi,Aynı anda iki kahve kapasitesiyle yığılmayı önleyen ve farklı kahve seçenekleri sunan bir kahve makinesi,Coffee machine for offices and shared spaces,A coffee machine that prevents queuing with dual-cup brewing capacity and offers a variety of coffee selections.,ChatGPT; Gemini; Vizcom,cover/061.jpg,logbook/061.pdf
62,Yağmur,Gür,2,Türk Çayı ve Türk Kahvesi Makinesi,Proje; marine yaşam ortamları için kompakt bir çoklu içecek makinesi tasarlamayı amaçlamaktadır. Bu makine; hem aynı anda hem de ayrı ayrı tek bir tuşla Türk çayı ve Türk kahvesi hazırlayabilirken; aynı zamanda alan kısıtı; kablo düzeni ve cihaz karmaşası sorunlarını çözmeyi hedeflemektedir. Tasarım ayrıca Türk içecek kültürünün ritüel ve keyif odaklı yönünü orta–üst gelirli yat sahiplerine tanıtmayı amaçlamaktadır.,Turkish Tea & Turkish Coffee Machine,The project aims to design a compact multi-beverage machine for marine living environments. This machine can prepare Turkish tea and Turkish coffee with a single button; either simultaneously or separately; while also addressing space limitations; cable management issues; and appliance clutter. The design also aims to introduce the ritual and pleasure-oriented culture of Turkish beverages to middle-upper income yacht owners.,ChatGPT; Gemini; Vizcom,cover/062.jpg,logbook/062.pdf
63,Altuğ,Erken,2,Seyahat Tipi Demleme Termosu,Nomad Brewer; doğa tutkunları ve sürekli hareket halindeki bireyler için tasarlanmış; su ısıtma; demleme ve içme fonksiyonlarını ultra hafif; dayanıklı ve modüler tek bir gövdede birleştiren hepsi bir arada taşınabilir çay ekosistemidir.,Nomad Brewer,Nomad Brewer is an all-in-one portable tea ecosystem designed for outdoor enthusiasts and individuals constantly on the move; combining water heating; brewing; and drinking functions within a single ultra-light; durable; and modular body.,ChatGPT; Gemini; NotebookLM,cover/063.jpg,logbook/063.pdf
64,Ayla,Asgarova,2,Türkçe Başlık,Proje kısa açıklaması,English Heading,Short project description,ChatGPT; Gemini; Vizcom,cover/064.jpg,logbook/064.pdf
65,Bahar,Kabayuka,2,Kullanıcı Odaklı ve Uyarlanabilir Filtre Kahve Makinesi Tasarımı,Bu proje; kullanıcıların farklı kahve tercihlerine uyum sağlayan kullanıcı odaklı bir filtre kahve makinesi tasarlamayı amaçlamaktadır. Ayarlanabilir asansör sistemi sayesinde hem tek fincan hem de sürahi ile demleme yapılabilir. Çekmeli su haznesi; kendiliğinden sepetli filtre ve silikon kaymaz taban kullanım kolaylığı sağlar. Ayrıca aroma ayarı ve tebeşirli not alanı ile ürün fonksiyonel ve etkileşimli bir deneyim sunar.,Adaptive and User-Centered Filter Coffee Machine Design,This project aims to design a user-centered filter coffee machine that adapts to different coffee preferences. The adjustable elevator system allows brewing with either a single cup or a glass carafe. A pull-out water tank; built-in filter basket; and silicone anti-slip base improve usability. Aroma control and a chalkboard note area add both functional and interactive features to the product.,ChatGPT; Gemini; Vizcom,cover/065.jpg,logbook/065.pdf
66,Defne,Taydaş,2,Restea: Tek kişilik elektrikli çay demleme cihazı.,Restea; gün içinde yoğun çalışmanın ardından dinlenmeye ihtiyaç duyan kişiler için tasarlanmış bir çay demleme cihazıdır. Çay yapma eylemini bilinçli ve sakinleştirici bir ritüele dönüştürür. Şeffaf borosilikat cam gövde; çayınızın renginin yavaşça derinleşmesini izlemenizi sağlar. Demleme tamamlandığında; pistona nazikçe yapılan bir baskı yaprakları sıkıştırır. Tek bir düğmeye basarak yapraklar çöp kutusuna temizce düşer ve elleriniz yapraklara hiç dokunmaz.,Restea: A single-serve electric tea brewing device that helps you transition into a break after mental fatigue during the day; designed for effortless cleaning.,Restea is a tea brewing device designed for people who need rest after a hardwork during the day's work. It transforms the act of tea brewing into a mindful and calming ritual. The transparent borosilicate glass body lets you watch your tea deepen in color. When steeping is done; a gentle push of the piston compresses the leaves. A single button releases them cleanly into the bin and your hands never touch the leaves.,ChatGPT; Gemini; Vizcom; Claude,cover/066.jpg,logbook/066.pdf
67,Duru,Hotanoğlu,2,Kullanıcıyı Ana Döndüren Kapsül Kahve Makinesi,Bu kapsül kahve makinesi; kahve hazırlama sürecini farkındalık içeren bir ritüele dönüştürür. Kahve hazırlanırken cihaz; kullanıcının çevresindeki sesleri; kokuları ve nefesini fark etmesini teşvik eden kısa yönlendirmeler sunarak onların ana dönmesine yardımcı olur.,A Capsule Coffee Machine that Brings Users Back to the Present Moment,This capsule coffee machine turns coffee preparation into a mindful ritual. While the coffee is being prepared; the device provides short prompts that encourage the user to notice their surroundings and breathing; helping them return to the present moment.,ChatGPT; Gemini,cover/067.jpg,logbook/067.pdf
68,Gülin,Ülger,2,Görme Engelli Bireyler İçin Çaycı,Çay demleme sürecini güvenli hale getirme.,Tea Maker for Visually Impaired Individuals,To make the tea brewing process safe.,ChatGPT; Gemini; Vizcom,cover/068.jpg,logbook/068.pdf
69,İpek,Özemre,2,Termoslu Kapsül Kahve Makinesi,Makinenin ağız kısmına kolayca takılıp çıkarılabilen termosuyla birlikte bu kapsül kahve makinesi dökülme ve sıçrama riskini azaltır.,Screw-on Pod Coffee Machine,This pod coffee machine reduces the risk of spills and splashes with its thermos that can be easily attached to the machine's spout,ChatGPT; Gemini,cover/069.jpg,logbook/069.pdf
70,Merve,Aral,2,Taze Meyve Demleyici,Taze meyve çayı için kaynatma; demleme; ve içme özelliklerini tek bir bünyede toplayan ısıtmalı termos kupa,Personal Fruit Tea Steeper,A self-heating cup that lets you boil; brew; and drink fresh fruit tea in one place,Claude; Gemini; Vizcom; Firefly,cover/070.jpg,logbook/070.pdf
71,Mina,Sarıçam,2,Seremoniyel Kakao Makinesi,Yoga pratiğinden önce tüketilen seremoniyel kakaoyu hazırlamak için tasarlanmış; termos formunda yarı taşınabilir bir ısıtmalı blender makinesidir.,Ceremonial Cacao Machine,A semi-portable heated blender machine designed in a thermos form to prepare ceremonial cacao consumed before a yoga practice,ChatGPT; Gemini; Vizcom,cover/071.jpg,logbook/071.pdf
72,Naz,Yavuz,2,Yaşlılar İçin Bitki Çayı Demleyici,Öğrenilmiş bağımlılık hissini yıkmak için kullanım kolaylığı sağlayan demleyici,Tea brewer for elderly people,A brewer that makes it easy to use; helping you break free from the feeling of learned dependency,ChatGPT;Gemini;Vizcom,cover/072.jpg,logbook/072.pdf
73,Nur,Kazancı,2,Artisanal Chado: Hijyenik Matcha Hazırlama İstasyonu,Geleneksel Japon çay ritüelini modern mühendislikle birleştiren bu cihaz; step motor teknolojisi ve özel kenetlenme mekanizması sayesinde etrafa sıçratmadan; ideal 80°C sıcaklıkta kusursuz matcha hazırlar.,Artisanal Chado: Mess-Free Matcha Preparation Station,"Merging traditional Japanese ritual with modern engineering; this device utilizes a NEMA 17 stepper motor and a unique ""whisk-in-jar"" coupling system to prepare perfect matcha at 80°C without any mess.",Gemini; Vizcom,cover/073.jpg,logbook/073.pdf
74,Talha,Felek,2,Termos Kettle,Kullanıcının kendi içecek ritüelini (çay/kahve) dilediği her yerde profesyonel standartlarda hazırlamasına olanak tanır.,Portable All-in-One Brewing System,Ritual Station is a portable brewing system designed to liberate personal hot beverage rituals from location-based dependencies. Integrating a precision OLED-controlled heating system with a manual French Press mechanism; the device empowers users to prepare high-quality coffee or tea anywhere. It bridges the gap between digital accuracy and tactile craftsmanship; offering a complete; self-contained brewing experience for the modern nomad.,ChatGPT; Gemini;,cover/074.jpg,logbook/074.pdf
75,Yasemin,Avdagiç,2,Ofis İçin Kahve Makinesi,Paylaşımlı alanlar için hijyenik ve efektif kahve deneyimi sağlayıcı,Office Coffee Machine,A hygienic and effective coffee experience provider for shared spaces,Gemini; Vizcom,cover/075.jpg,logbook/075.pdf
76,Ada,Salar,3,Herballistic,Herballistic kurutulmuş bitkilerden önce aromatik buhar salarak difüzör gibi çalışan ardından aynı bitkileri demleyerek çay hazırlayan bir çay makinesidir. Kullanıcının önce bitkinin kokusunu deneyimleyip sonra içmesini sağlayarak çay hazırlama sürecini koku; sıcaklık ve tat arasında çok duyulu bir ritüele dönüştürür.,Herballistic,Herballistic is a tea machine that functions both as a herbal diffuser and a brewing device; releasing aromatic steam from dried herbs before they are infused in water. By allowing users to first inhale the herbs and then drink them; the machine transforms tea preparation into a multi-sensory ritual connecting scent; warmth; and taste.,ChatGPT; Gemini; Vizcom,cover/076.jpg,logbook/076.pdf
77,Almina,Akbay,3,Arc,Arc; farklı çay ve bitki demleme yöntemlerini birleştiren çok yönlü bir çay demleme cihazıdır. Kullanıcıya; bitkilerin porsiyon boyutlarını ve demleme işlemi sırasında su sıcaklığını seçme olanağı sunarak; çayın aromasını ve karakterini kişisel tercihlerine göre özelleştirme imkanı tanır. Modern teknolojiyi kadim çay ritüelleriyle harmanlayan bu sistem; özellikle yoğun bir iş gününün ardından; kullanıcının günlük hayatın temposundan uzaklaşmasını sağlayarak bir kaçış anı yaratmayı amaçlamaktadır. Hassas dozlama ile başlayan bu özenli süreç; demleme işlemi sırasında pürüzsüz; kontrollü bir laminar akışla sonuçlanır. Mat siyah çeliğin zarafetini ahşabın sıcaklığıyla birleştiren Arc; her fincanda sadece çay değil; aynı zamanda kullanıcı için kişisel bir huzur alanı da yaratır.,Arc,Arc is a versatile tea brewing device that combines different tea and herb brewing methods. It allows the user to customize the aroma and character of the tea according to personal preferences by offering the ability to select both the portion sizes of the herbs and the water temperature during the brewing process. This system; which blends modern technology with ancient tea rituals; aims to create a moment of escape; especially after a busy workday; allowing the user to step away from the pace of daily life. This mindful process; starting with precise dosing; culminates in a smooth; controlled laminar flow during the brewing process. Combining the elegance of matte black steel with the warmth of wood; Arc brews not only tea in every cup; but also a personal space of tranquility for the user.,ChatGPT; Gemini; Vizcom; Manus,cover/077.jpg,logbook/077.pdf
78,Arda,Dündar,3,ModuBrew,ModuBrew; kahve tozu ve filtre kağıdı depolamasını doğrudan sistemine entegre eden; daha düzenli ve pratik bir demleme deneyimi sunan modüler bir filtre kahve makinesidir.,ModuBrew,ModuBrew is a modular filter coffee machine that integrates storage for coffee powder and filter papers directly into the system; creating a more organized and convenient brewing experience.,ChatGPT; Gemini,cover/078.jpg,logbook/078.pdf
79,Baran,Ay,3,Phase,Phase; geleneksel matcha ritüelinin özünü korurken onu çağdaş günlük yaşama uyarlayan bir üründür. Tasarım; el ile çırpma deneyimi ve seremonik hissi devam ettirirken hazırlık sürecini daha pratik; düzenli ve erişilebilir hale getirmeyi amaçlar.,Phase,Phase is a product that adapts the essence of the traditional matcha ritual to contemporary daily life. While maintaining the hand-whisking experience and ceremonial feeling; the design aims to make the preparation process more practical; organized; and accessible.,ChatGPT; Gemini; Vizcom,cover/079.jpg,logbook/079.pdf
80,Beyza,Dinçer,3,Orbit Kahve Sistemi,Orbit Coffee System; paylaşılan ortamlarda kişiselleştirilmiş kahve deneyimi sunan bir kahve makinesidir. Kullanıcılar kendi tokenlarını takarak makinenin onları tanımasını ve tercih ettikleri kahveyi otomatik olarak hazırlamasını sağlar. Minimal arayüz ve fiziksel etkileşim sayesinde kahve hazırlama süreci hızlı ve sezgisel bir ritüele dönüşür.,Orbit Coffee System,Orbit Coffee System is a coffee machine designed to deliver a personalized experience in shared environments. Users insert their personal token; allowing the machine to recognize them and automatically prepare their preferred drink. With its minimal interface and physical interaction; Orbit turns coffee preparation into a simple and intuitive ritual.,ChatGPT; Gemini; Vizcom,cover/080.jpg,logbook/080.pdf
81,Bora,Yenigün,3,BrewGo,BrewGo; sabahları zamanı kısıtlı olan kullanıcılar için tasarlanmış bir filtre kahve makinesidir. Kahveyi doğrudan termosun içine demleyerek kullanıcıların kahvelerini hızlı ve pratik bir şekilde hazırlamalarını sağlar. Böylece kullanıcılar kahvelerini beklemeden alıp evden çıkabilirler. Dokunmatik ekran ve mobil uygulama üzerinden demleme ayarları kolayca kontrol edilebilir ve sistem sabah rutinini daha verimli hale getirmeyi amaçlar.,BrewGo,BrewGo is a filter coffee machine designed for people who have limited time in the morning. It brews coffee directly into a thermos; allowing users to prepare their coffee quickly and efficiently. This enables users to take their coffee and leave without waiting. The brewing process can be controlled through a touchscreen interface and a mobile application; helping to make the morning routine more efficient and convenient.,ChatGPT; Vizcom,cover/081.jpg,logbook/081.pdf
82,Damla,Genel,3,Çok Cezveli Türk Kahvesi Hazırlama Cihazı,Türk kahvesinin geleneksel cezve yöntemiyle kalabalık ortamlar için aynı anda ve farklı şeker tercihlerine uygun şekilde hazırlanmasını sağlayan; sosyal etkileşimi destekleyen; taşmayı önleyen ve hazırlama sürecini kolaylaştıran bir kahve hazırlama cihazıdır.,Multi-Cezve Turkish Coffee Preparation Device,A Turkish coffee preparation device designed for crowded environments that enables the simultaneous preparation of multiple coffees with different sugar preferences while supporting social interaction; preventing overflow; and simplifying the preparation process.,ChatGPT; Gemini; Vizcom,cover/082.jpg,logbook/082.pdf
83,Damlanur,Ağdacı,3,Bloom,Bloom; otomatik sıcaklık kontrolü; iki aşamalı blooming demleme ve dönen demleme haznesi ile tutarlı kahve demleme sağlayan akıllı bir kahve hazırlama sistemidir. Mobil uygulama üzerinden kullanıcılar demleme ayarlarını yapabilir; kafein tüketimini takip edebilir ve kahve telvesini bağışlayarak sürdürülebilir bir deneyime katkı sağlayabilir.,Bloom,Bloom is a smart coffee preparation system that ensures consistent brewing through automated temperature control; two-stage blooming extraction; and a rotating brewing chamber. The mobile app allows users to adjust brewing settings; track caffeine intake; and optionally donate used coffee grounds; creating a seamless and sustainable coffee experience.,ChatGPT; Gemini; Vizcom; Whisk,cover/083.jpg,logbook/083.pdf
84,Defne,Öztosun,3,İş Akışına Uyumlu Akıllı Kahve Makinesi,Flow Synced Brew; evden çalışan kullanıcıların günlük iş akışını kesintiye uğratmadan kahve hazırlamalarını sağlayan akıllı bir kahve makinesidir. Mobil uygulama üzerinden gönderilen demleme komutları sayesinde hızlı ve pratik bir kullanım sunar.,Flow Synced Brew – Coffee Machine,Flow Synced Brew is a smart coffee machine designed for remote workers; allowing them to prepare coffee without interrupting their daily workflow. Through brewing commands sent via a mobile application; it provides a fast and convenient user experience.,ChatGPT; Vizcom,cover/084.jpg,logbook/084.pdf
85,Derin,Seren,3,Kahve Makinesi,,Coffee Maker,,ChatGPT; Gemini; Vizcom,cover/085.jpg,logbook/085.pdf
86,Ece,Kandemir,3,BrewLab - Filtre Kahve Makinesi,BrewLab; kahve demlemede en çok tercih edilen pour-over yöntemini gelişmiş mekanizmasıyla yeniden yorumlayan bir filtre kahve makinesidir. Demleme sürecini görünür kılarak kullanıcı ile kahvenin yolculuğu arasındaki etkileşimi sürekli ve deneyimsel hale getirir.,BrewLab - Filter Coffee Machine,BrewLab is a filter coffee machine that reinterprets the widely preferred pour-over brewing method with an advanced mechanism. By making the brewing process visible; it creates a continuous and experiential interaction between the user and the journey of the coffee.,ChatGPT; Gemini; Vizcom; LeonardoAI,cover/086.jpg,logbook/086.pdf
87,Efecan,Elçiçek,3,Heritage Precision,Heritage Precision; dijital hassasiyet ile kahve hazırlama ritüeli arasındaki gerilimi yeniden yorumlayan lüks bir lever espresso makinesidir. Tasarım; mühendislik doğruluğunu ekranlar veya sayısal göstergeler yerine fiziksel etkileşimlerin içine yerleştirir. Kalibre edilmiş kol hareketi; tırtıklı ayar düğmesinin dönüş hissi ve kusursuz malzeme geçişleri sayesinde kullanıcı hassasiyeti görerek değil; dokunarak ve hissederek deneyimler.,Heritage Precision,Heritage Precision is a luxury lever espresso machine that reinterprets the relationship between digital precision and tactile ritual. Instead of relying on screens or numerical displays; engineering accuracy is embedded into every physical interaction. From the calibrated lever pull to the knurled dial rotation and seamless material transitions; the machine allows users to experience precision through touch and movement rather than visual feedback.,ChatGPT; Gemini; Vizcom,cover/087.jpg,logbook/087.pdf
88,Elif,Doğan,3,Infusia,fiziksel arayüze sahip kullanıcıyı yormayan ritüel ağırlıklı retro görünüme sahip bitki çayı demleme makinesi,Infusia,A retro-style herbal tea brewing machine with a physical interface; designed to be effortless for the user and centered around a ritualistic experience.,ChatGPT; Gemini; Vizcom,cover/088.jpg,logbook/088.pdf
89,Elif,Keskin,3,Brewsense - Akıllı Bitki Çayı Demleme Sistemi,Bu proje; farklı bitki türlerinin uygun sıcaklık ve demleme süreleriyle hazırlanmasını sağlayan akıllı bir bitki çayı demleme sistemi tasarlamayı amaçlamaktadır. Sistem; bitkilerin doğru şekilde karıştırılmasını; demleme parametrelerinin kontrol edilmesini ve tutarlı bir çay deneyimi elde edilmesini destekler.,BrewSense – Smart Herbal Tea Brewing System,This project aims to design a smart herbal tea brewing system that enables different types of herbs to be prepared with appropriate temperatures and steeping times. The system supports accurate herb mixing; control of brewing parameters; and the creation of a consistent tea experience.,ChatGPT; Gemini; Vizcom; Canva AI,cover/089.jpg,logbook/089.pdf
90,Emine,Küçük,3,UniBrew,UniBrew; küçük yaşam alanlarında çay ve kahve hazırlama ihtiyacını tek bir kompakt cihazda birleştirmek amacıyla tasarlanmış çok fonksiyonlu bir sıcak içecek makinesidir.Farklı demleme yöntemlerini tek sistemde toplayarak yer tasarrufu sağlayan; sade ve anlaşılır bir kullanım sunar.Şeffaf demleme haznesi hazırlama sürecini görünür kılarken; üst kontrol paneli porsiyon ve içecek seçimini kolaylaştırır.,UniBrew,UniBrew is a multifunctional hot beverage machine designed to combine tea and coffee preparation in a single compact device for small living spaces.It brings different brewing methods together in one system; offering a space-saving and intuitive user experience. The transparent brewing chamber makes the process visible; while the top control panel allows easy selection of portion size and beverage type.,ChatGPT; Gemini; Vizcom,cover/090.jpg,logbook/090.pdf
91,Emir,Akalın,3,Fermata,Fermata; kahve demlemenin sıradan rutinine dahil olan ve bunu dijital ile fiziksel dünyalar arasında bir eşik olarak kabul eden bir istasyondur. Hız çağında Fermata; bilinçli bir organize farkındalık sığınağı yaratır.,Fermata,Fermata is a station that gets involved in the mundane routine of brewing coffee and recognizes it as a threshold between the digital and physical worlds. In an era of fast pace; Fermata creates a sanctuary of intentionality.,Gemini; Vizcom,cover/091.jpg,logbook/091.pdf
92,Emre,Özlük,3,Dripturn Modüler Demleme Ünitesi,Dripturn modüler demleme ünitesi 4 parçadan oluşur ve Kamp yapmayı seven kullanıcılara etkinlik anında hem kahve hemde çay demleme seçenekleri sağlar. Ürünün Isıtma modülünde ısıtılan su ünitenin ters çevrilmesi ile birlikte filtreden geçerek termos yapısına sahip dağıtım ve içme ünitesine akar.,Dripturn Modular Brewing Unit,The Dripturn modular brewing unit consists of 4 parts and provides users who enjoy camping with the option of brewing both coffee and tea on the spot. Water heated in the heating module flows through a filter into the thermos-like dispensing and drinking unit when the unit is inverted.,ChatGPT; Gemini; Vizcom; Claude AI,cover/092.jpg,logbook/092.pdf
93,Gizem,Yıldırım,3,Crema - Yarı Otomatik Espresso Makinesi,Minimalist; doğadan ilham alan; tezgah üstünde az yer kaplayan ve kullanımı kolay yarı otomatik espresso makinesi.,Crema - Semi Automatic Espresso Machine,A minimalist; nature-inspired; countertop-sized; and easy-to-use semi-automatic espresso machine.,ChatGPT; Gemini; Vizcom,cover/093.jpg,logbook/093.pdf
94,Gülce,Erginer,3,InfiniTea,InfiniTea; kum saatinden ilham alan bir çay demleme sistemidir. Yerçekimi ve dönüş hareketiyle çay hazırlamayı sakin ve kontrollü bir ritüele dönüştürür.,InfiniTea,InfiniTea is a tea brewing system inspired by the hourglass. Using gravity and rotation; it turns tea making into a calm and precise ritual.,ChatGPT; Vizcom,cover/094.jpg,logbook/094.pdf
95,İpek,İnan,3,Demista,Demista; geleneksel Türk çay seremonisini modern tasarım hatlarıyla yeniden yorumlayan; kuru çaydan bardağa süreci zarafetle buluşturan ikonik bir tasarımdır.,Demista,Demista; an iconic design that reimagines the traditional Turkish tea ceremony with modern design lines; elegantly bridging the journey from loose tea to the cup.,ChatGPT; Gemini; Vizcom,cover/095.jpg,logbook/095.pdf
96,Irmak,Halıcı,3,Telvora,Telvora; geleneksel Türk kahvesi ritüelini dairesel bir yörüngede buluşturan; ofis içi paylaşım odaklı bir buluşma noktasıdır.,Telvora,Telvora is a shared-oriented meeting point that brings the traditional Turkish coffee ritual together in a circular orbit for modern office environments.,ChatGPT; Gemini; Vizcom,cover/096.jpg,logbook/096.pdf
97,Meltem,Karayılan,3,CupZone,CupZone; poşet bitki çaylarını zahmetsiz ve kontrollü şekilde demlemek için tasarlanmış kompakt bir tek porsiyon çay istasyonudur. Yeniden kullanılabilir infuser kartuşu sayesinde kullanıcı; çay poşetini cihazın içine yerleştirir ve tek dokunuşla demleme sürecini başlatır. Kartuş; ideal sıcaklığa ulaşan suya otomatik olarak indirilir ve belirlenen süre sonunda yukarı alınarak demleme durdurulur. Özel damlama önleyici taban; kartuş yukarı çıktığında kalan sıvıyı içinde tutarak cezveye geri damlamayı engeller ve çayın aşırı demlenmesini önler. Sızdırmaz kapak yapısı; ısıyı içeride tutarak enerji verimliliğini artırır ve güvenli kullanım sağlar. Şeffaf cam cezve; demleme sürecini izlemeye olanak tanırken ergonomik formu kolay servis imkânı sunar. Cihazın her iki yanında yer alan entegre servis tepsileri; poşet çay; şeker; limon ve fincan gibi tamamlayıcı unsurları düzenli biçimde bir arada tutarak çay hazırlama ritüelini tek noktada toplar. Modern; sade ve dayanıklı malzeme diliyle tasarlanan CupZone; günlük kullanım için pratik bir çözüm sunarken mutfak tezgâhında estetik bir odak noktası oluşturur. Tek fincanlık bitki çayını hızlı; temiz ve tutarlı şekilde hazırlamak isteyen kullanıcılar için işlevsel ve zarif bir deneyim sunar.,CupZone,CupZone is a compact single-serving tea station designed for effortless and controlled brewing of herbal tea bags. Thanks to its reusable infuser cartridge; the user simply places the tea bag inside the device and starts the brewing process with a single touch. The cartridge automatically lowers into the water when it reaches the ideal temperature and is raised to stop brewing after the set time. The special drip-free base prevents liquid from dripping back into the pot when the cartridge rises; preventing over-brewing. The leak-proof lid keeps heat inside; increasing energy efficiency and ensuring safe use. The transparent glass pot allows you to monitor the brewing process; while its ergonomic shape offers easy serving. Integrated serving trays on either side of the device keep complementary items such as tea bags; sugar; lemon; and cups neatly organized; bringing the tea-making ritual together in one place. Designed with a modern; simple; and durable material language; CupZone offers a practical solution for daily use while creating an aesthetic focal point on your kitchen counter. It offers a functional and elegant experience for users who want to prepare single-serving herbal teas quickly; cleanly; and consistently.,ChatGPT; Gemini,cover/097.jpg,logbook/097.pdf
98,Mert,Delikaya,3,Tempo,Tempo; dokunsal ve manuel bir akşam ritüelinden alarm tetiklemeli bir otomasyona geçiş yapan; kullanıcının uyanır uyanmaz anında çayına kavuşması için makineyi önceden hazırlamasına olanak tanıyan bir demleme sistemidir.,Tempo,Tempo is an adaptive brewing system that shifts from a tactile; hands-on evening ritual to an alarm-triggered automation; allowing the user to prep the machine in advance for immediate tea upon waking.,Gemini; Vizcom,cover/098.jpg,logbook/098.pdf
99,Mert,Tiryaki,3,Otto - Türk Kahvesi Makinesi,Otto; butik ofislerdeki hız ihtiyacı ile Türk kahvesinin geleneksel ritüelini; akıllı dozajlama teknolojisi ve kullanıcıyı sürece dahil eden şeffaf tasarımıyla dengeleyen bir kahve makinesidir.,Otto - Turkish Coffee Machine,Otto is a coffee machine that balances the need for speed in boutique offices with the traditional ritual of Turkish coffee; through intelligent dosing technology and a transparent design that engages the user in the process.,ChatGPT; Gemini; Vizcom; Manus,cover/099.jpg,logbook/099.pdf
100,Nefin,Cantürk,3,Kanso,Bu proje; matcha felsefesi ve ritüelinin çağdaş şehir yaşamının temposuna nasıl uyarlanabileceğini araştırmaktadır. Amaç; yoğun günlük rutinler içinde zihinsel denge ve kısa yavaşlama anları arayan modern şehir profesyonelleri için matcha hazırlama sürecini bilinçli bir günlük ritüele dönüştüren bir ürün tasarlamaktır. Proje; geleneksel matcha kültürünün unsurlarını modern ürün tasarımıyla birleştirerek yarı otomatik bir hazırlama deneyimi sunmayı hedefler. Böylece süreç hem pratik kalırken hem de ritüelin anlamı ve kullanıcıyla olan etkileşimi korunur. Tasarımın amacı yalnızca bir içecek hazırlamak değil; aynı zamanda günlük yaşam içinde 3–5 dakikalık bilinçli bir geçiş ve odaklanma anı yaratmaktır.,Kanso,This project explores how the philosophy and ritual of matcha can be adapted to the pace of contemporary urban life. It aims to design a product that transforms matcha preparation into a short but intentional daily ritual for modern urban professionals who seek moments of slowing down and mental balance within their busy routines. By combining elements of traditional matcha culture with modern product design; the system creates a semi-automated preparation experience that remains practical while preserving the meaning and engagement of the ritual. The goal is not only to prepare a beverage; but to offer a 3–5 minute mindful transition that supports focus; calmness; and sustainable energy within everyday life.,ChatGPT; Gemini;,cover/0100.jpg,logbook/0100.pdf
101,Nil,Baykan,3,TeA Taze Çay Öğütme ve Demleme Sistemi,TeA; öğütme ve demleme sistemini tek üründe birleştiren elektrikli bir çay makinesidir. Kullanıcı çay yapraklarını grinder haznesine koyar; öğütülen çay filtreye düşer ve kettle suyu ısıtarak taze çayı otomatik olarak demlemeye başlar.,TeA Fresh Tea Grinding & Brewing System,TeA is an electric tea maker that combines a grinder and a brewing system in one product. The user adds loose tea leaves into the grinder; which grinds them and releases them into a filter. Then the kettle heats the water and brews fresh tea automatically.,ChatGPT; Vizcom,cover/0101.jpg,logbook/0101.pdf
102,Pelin,Turan,3,Lattenza -Espresso Makinesi,Lattenza; küçük yaşam alanlarında (öğrenci evleri; genç çiftlerin mutfakları) yer tasarrufu sağlayan; su tankı; kahve öğütücüsü ve süt haznesini tek bir gövdede birleştiren  kompakt bir espresso makinesidir. Hızlı sabah rutinlerine sahip kullanıcılar için tasarlanan bu cihaz; kişisel profil kaydetme özelliğiyle favori kahve tariflerini tek tuşla hazırlar; aynı zamanda sezgisel dokunmatik ekranı sayesinde farklı içecek türleri ve misafir ikramları için anlık; pratik bir kullanım sunar.,Lattenza - Espresso Machine,Lattenza is a compact espresso machine that saves space in small living areas (student apartments; young couples' kitchens) by combining the water tank; coffee grinder; and milk container in a single unit. Designed for users with fast morning routines; this device prepares favorite coffee recipes with a single touch thanks to its personal profile saving feature; it also offers instant; practical use for different types of drinks and serving guests thanks to its intuitive touchscreen.,ChatGPT; Gemini; Vizcom; Manus,cover/0102.jpg,logbook/0102.pdf
103,Selin,Dengiz,3,Hızlı Sabah Rutinleri İçin Görünür Demleme Süreci Sunan Akıllı Çok Kullanıcılı Kahve Makinesi,Bu proje; yoğun sabah rutinlerine sahip kullanıcılar için tasarlanmış akıllı ve çok kullanıcılı bir kahve makinesi konseptini ele almaktadır. Tasarım; kullanıcıdan alınan girdiyi en aza indirerek kahve hazırlama sürecini hızlandırmayı ve aynı zamanda demleme aşamalarını görünür hale getirerek sürecin daha anlaşılır olmasını amaçlamaktadır. Sistem; tek seferde komut girme; kullanıcı profilleri ve çok kullanıcılı sıra yönetimi gibi özellikler sayesinde paylaşılan yaşam alanlarında kahve hazırlama deneyimini daha hızlı; düzenli ve şeffaf hale getirir.,Smart Multi-User Coffee Machine with Visible Brewing for Faster Morning Routines,This project proposes a smart multi-user coffee machine designed for busy morning routines; focusing on minimizing user input while enabling the fastest possible brewing process. By combining visible brewing stages; household user profiles; and a queue-based system; the design creates a more transparent and efficient coffee preparation experience for shared living environments.,ChatGPT; Gemini; Vizcom,cover/0103.jpg,logbook/0103.pdf
104,Selin,Özkaya,3,Akıllı Bitki Çayı Makinesi,Kullanıcının ihtiyacına göre bitki çayını otomatik hazırlayan akıllı bir mutfak cihazıdır. Dokunmatik ekran üzerinden seçilen etkiye göre uygun bitki karışımını demleyerek çayı hazırlar.,Smart Herbal Tea Machine,A smart kitchen device that automatically prepares herbal tea based on the user’s needs. The touchscreen allows users to choose an effect; and the machine brews the suitable herbal blend.,ChatGPT,cover/0104.jpg,logbook/0104.pdf
105,Sude,Söylemez,3,Lezzet Profili Temelli Tarif Rehberli Kahve Makinesi,Bu proje; kullanıcıların kahve seçimi sırasında yaşadığı karar karmaşasını azaltmayı amaçlayan tarif rehberli bir kahve makinesi konseptini araştırır. Sistem; makineye yüklenen kahve çekirdeğinin lezzet profilini temel alarak kısa ve yapılandırılmış bir seçim süreci sunar ve kullanıcıya tek; optimize edilmiş bir içecek önerisi oluşturur. Böylece öneriler hem kullanıcının o anki ruh hâline hem de kullanılan çekirdeğin aromatik karakterine uyum sağlayacak şekilde adapte edilir.,Recipe-Guided Coffee Machine with Flavor-Profile-Based Bean System,This project explores a recipe-guided coffee machine designed to reduce beverage decision fatigue. The system uses the flavor profile of the loaded coffee beans to guide users through a short; structured selection process and generates one optimized drink recommendation. The suggestion adapts dynamically to both the user’s current mood and the aromatic identity of the beans.,ChatGPT; Gemini; Vizcom,cover/0105.jpg,logbook/0105.pdf
106,Yağız,Edirne,3,Molín,Molín; champurrado içeceğinin geleneksel hazırlanış ritüelini modern kafe ortamında görünür kılmak için tasarlanmış bir hazırlama sistemidir. Manuel molinillo hareketini koruyarak hazırlama sürecini mekânsal olarak vurgular.,Molín,Molín is a preparation system designed to highlight the traditional ritual of champurrado making in a contemporary café environment. It preserves the manual molinillo motion while visually amplifying the process.,ChatGPT,cover/0106.jpg,logbook/0106.pdf
107,Zeynep,Kandemirli,3,SmartRise – Kompakt Filtre Kahve Makinesi,Küçük mutfaklarda yaşayan ve sabahları hızlı olmak isteyen bireyler için tasarlanmış akıllı; kompakt kahve makinesi. Taze kahve; porsiyon kontrolü; kolay temizlik ve özelleştirilebilir demleme özelliklerini mobil uygulama ve günlük otomasyonla birleştirerek sabah rutinlerini basitleştirir. Minimum çaba; maksimum kolaylık için ideal.,SmartRise – Compact Filter Coffee Machine,A smart; compact coffee machine designed for early risers living alone in small kitchens. It simplifies morning routines by combining freshness; portion control; easy cleaning; and customizable brewing with app integration and daily automation. Perfect for users who want minimal effort and maximum convenience.,ChatGPT; Gemini; Vizcom,cover/0107.jpg,logbook/0107.pdf
108,Zeynep,Tuğsal,3,Infiora – Hassas Bitki ÇayıDemleme Makinesi,Infiora; hassas ısı kontrolü ve dijital zamanlama algoritmasıyla; bitki çay çeşitlerini yakmadan en ideal değerlerde hazırlayan yüksek performanslı bir demleme makinesidir.,Infiora – Precision Herbal Infusion Machine,Infiora is a high-performance brewing machine that prepares various herbal teas at their ideal values; without scorching them; thanks to its precision temperature control and digital timing algorithm.,ChatGPT; Gemini; Vizcom,cover/0108.jpg,logbook/0108.pdf
109,Zeynep,Vural,3,Being,Being;Bitki çayı içmeyi bir deneyim haline getirerek kullanıcıları için stressiz bir akış oluşturmayı hedefler,Being,Being aims to create a stress-free experience for its users by making herbal tea drinking an enjoyable experience.,Gemini; Vizcom,cover/0109.jpg,logbook/0109.pdf
110,Lara,Coşkun,4,Kompakt Sütlü Kahve Makinesi,Bu projede ev kullanımı için farklı sütlü kahve seçeneklerini hızlı ve pratik şekilde hazırlamayı sağlayan; kolay kullanımlı butonlara ve kullanıcıya geri bildirim veren dijital ekrana sahip kompakt bir kahve makinesi tasarladım.,Compact Milk-Based Coffee Machine,In this project I designed a compact coffee machine for home use that allows users to quickly and easily prepare different milk based coffee drinks; featuring simple control buttons and a digital display that provides user feedback.,ChatGPT; Gemini; Vizcom,cover/0110.jpg,logbook/0110.pdf
111,Sude,Doğanyiğit,4,BrewCore,Su ısıtma; çay ve kahve demleme süreçlerini kompakt ve çok amaçlı bir formda bir araya getiren; outdoor kullanıma uygun taşınabilir bir demleme cihazıdır.,Portable Stability × Multi-Usage in Mobile Living,It is a portable brewing device suitable for outdoor use; combining water heating; tea and coffee brewing processes in a compact and multi-usage form.,ChatGPT; Gemini; Vizcom,cover/0111.jpg,logbook/0111.pdf
112,Alena,Tokel,4,Chasena - Toz Bazlı Sıcak İçecek Hazırlama Makinesi,Matcha; hojicha ve kakao gibi toz bazlı içeceklerin hazırlanması için ev kullanıcılarına yönelik tasarlanmış bir tezgah üstü cihazdır. Hassas ölçüm sağlayarak hazırlama ritüelini sade ve kontrollü hale getirir.,Chasena - Hot Powder Beverage Machine,Hot Powder Beverage Machine,ChatGPT; Gemini; Vizcom; Claude; LM,cover/0112.jpg,logbook/0112.pdf
113,Ayşima,Güleçal,4,HaloFlow,HaloFlow; bitki çayı hazırlama sürecini yalnızca işlevsel bir işlem olmaktan çıkarıp sakin ve farkındalık odaklı bir ritüele dönüştürmeyi amaçlayan bir demleme cihazıdır. Halo formu sıcak suyun akışını yönlendirirken şeffaf demleme haznesi infüzyon sürecini görünür hale getirir. Böylece kullanıcı; bitki çayının hazırlanma sürecini gözlemleyerek duyusal ve katılımcı bir deneyim yaşar.,Herbal Infusion Ritual Device,It is a portable brewing device suitable for outdoor use; combining water heating; tea and coffee brewing processes in a compact and multi-purpose form.,ChatGPT; Gemini; Vizcom,cover/0113.jpg,logbook/0113.pdf
114,Deniz,Demirtürk,4,MoodT — Yurt Öğrencileri İçin Ruh Haline Duyarlı Bitki Çayı Karışım Makinesi,Bu çay makinesi yurtlarda yaşayan öğrencilerin farklı ruh halleri ve ihtiyaçlarına göre bitki çayı karışımları hazırlayan paylaşımlı bir demleme makinesidir. Sistem; odaklanma; rahatlama ve uyku gibi durumlara yönelik bitkileri otomatik olarak karıştırarak hızlı ve erişilebilir bir içecek deneyimi sunar.,MoodT — A Mood-Responsive Herbal Tea Blending Machine for Dorm Students,This tea machine is a shared brewing device designed to prepare herbal tea blends according to the different moods and needs of students living in dormitories. The system automatically mixes herbs for situations such as focus; relaxation; and sleep; offering a fast and accessible beverage experience.,ChatGPT; Gemini; Vizcom,cover/0114.jpg,logbook/0114.pdf
115,Duru,Cağlayan,4,SYNC – Çalışma Ritmine Uyum Sağlayan Filtre Kahve Makinesi,Tempo; paylaşımlı ofisler ve co-working ortamları için tasarlanmış bir filtre kahve makinesidir. Aynı anda birçok kişinin kahve almak istediği yoğun saatlerde ortaya çıkan kalabalık; sınırlı tezgâh alanı ve dikkat dağınıklığı gibi sorunlara çözüm sunar.,SYNC  – Filter Coffee Machine for the Rhythm of Work,Tempo is a filter coffee machine designed for shared office and co-working environments. It responds to the challenges of peak-hour use; where multiple people interact with the coffee machine at the same time while sharing limited countertop space.,ChatGPT; Vizcom,cover/0115.jpg,logbook/0115.pdf
116,Efe,Gezen,4,DERAKHT- Santrifüjlü Kahve Makinesi,Santrifüj ile demleme tekniğini kullanarak demlemenin her aşamasında kullanıcıya kontrol imkanı sunan; espresso; filtre kahve ve ikisinin arasındaki bütün kahve tarzlarını hazırlayabilen bir kahve makinesi.,DERAKHT- Centrifugical Coffee Maker,A coffee machine that utilizes centrifugal brewing technology to offer the user full control at every stage of the process; capable of preparing espresso; filter coffee; and every style in between.,ChatGPT; Gemini; Vizcom,cover/0116.jpg,logbook/0116.pdf
117,Elif,Mangıroğlu,4,Akıllı Süt Isıtma ve Köpürtme Sistemi,Bu konsept farklı içecekler için sütü doğru sıcaklıkta ısıtmak ve uygun köpük dokusunu oluşturmak üzere tasarlanmış bir tezgâh üstü cihazdır. Tüm içeceği hazırlamak yerine yalnızca süt hazırlama sürecine odaklanır ve bu işlemi tutarlı bir şekilde gerçekleştirir. Basit ve anlaşılır kullanıcı girdileri sayesinde kontrol ile sadelik arasında bir denge kurar ve matcha latte; chai latte; golden milk; sıcak çikolata ve süt bazlı kahve içecekleri gibi farklı içeceklerin hazırlanışını destekler.,Precision Milk Texturing System,This concept is a a countertop device designed to heat and texture milk with precision for a wide range of beverages. Rather than automating the entire drink; the system focuses on preparing milk correctly by adapting temperature and foam texture based on milk type and the intended beverage. It accommodates multiple drink cultures while allowing the user to prepare the base drink themselves.,ChatGPT; Gemini; Vizcom,cover/0117.jpg,logbook/0117.pdf
118,Hakan,Oral,4,Paylaşımlı Ofis Ortamları İçin Bakım Farkındalıklı Espresso Altyapısı,Bu proje; paylaşımlı ofis ortamlarında güvenilirlik ve kesintisiz kullanım ihtiyacını karşılamak üzere tasarlanmış bir espresso makinesi önermektedir. Sistem; yoğun kullanım saatlerinde kahve hazırlama sürecinin kesintiye uğramasını önlemek amacıyla engelleyici olmayan bakım mimarisi; öngörücü bakım göstergeleri ve görünür sistem durumu gibi özellikler sunmaktadır.,Maintenance-Aware Espresso Infrastructure for Shared Office Environments,This project proposes an espresso machine designed specifically for shared office environments where reliability and uninterrupted operation are critical. The system introduces a non-blocking maintenance architecture; predictive maintenance indicators; and visible system status to prevent brewing interruptions during peak usage periods.,ChatGPT,cover/0118.jpg,logbook/0118.pdf
119,Irmak,Özmenek,4,Bağlama Uyarlanabilir Ritüel Sistemi,"Bu kavram; anlamlı çaba ile bilişsel kolaylık arasındaki gerilimi çözüyor. ""anlamlı zorlanma""ya (ritüel moduna) olanak tanıyor ve manuel veya otomatik arasında ikili bir seçime zorlayan sensör kavramlarından oluşan bir ""güvenlik ağı"" aracılığıyla ""bilişsel kolaylık"" sağlıyor; bu kavram; kullanıcının psikolojik durumuna göre davranış biçimini değiştiren bir ""davranış sistemi"" gibi işlev görüyor.",Context-Adaptive Ritual System,"This concept resolves the tension between meaningful effort and cognitive convenience. It allows for ""meaningful exertion"" (ritual mode) and provides ""cognitive convenience"" through a ""safety net"" of sensor concepts that force a binary choice between manual and automatic; this concept functions like a ""behavioral system"" that changes the behavior according to the user's psychological state.",ChatGPT; Gemini; Vizcom,cover/0119.jpg,logbook/0119.pdf
120,Lara,Özpetek,4,Demli-Akıllı Türk Çayı Makinesi,Demli; Türk çayı hazırlama sürecini daha kontrollü ve pratik hale getirmek için tasarlanmış kompakt bir çay makinesidir. Kullanıcı makineye çay yapraklarını ve suyu ekler; ardından kaç kişilik çay hazırlanacağını seçer. Demleme tamamlandıktan sonra kullanıcı her bardak için istediği dem oranını (açık; orta; koyu) ayarlayabilir ve makine çayı buna göre bardağa döker. Bu sistem; Türk çayındaki geleneksel demleme mantığını korurken çay ve su miktarını daha kontrollü hale getirir. Böylece hem günlük kullanım kolaylaşır hem de fazla çay hazırlanmasından kaynaklanan israf azaltılır.,Demli-Smart Turkish Tea Machine,Demli is a compact Turkish tea machine designed to make tea preparation more controlled and convenient. The user first adds tea leaves and water into the machine; then selects the number of people the tea will be prepared for. Once the tea is brewed; the user can adjust the desired tea strength (light; medium; or strong) for each glass; and the machine dispenses the tea accordingly. By translating the traditional Turkish tea brewing logic into a controlled system; Demli helps users manage tea quantity and strength more easily while reducing unnecessary tea and water waste.,ChatGPT; Gemini; Vizcom,cover/0120.jpg,logbook/0120.pdf
121,Mediya,Acar,4,Sempres,Kahve yapmanın dokunsal keyfini korurken; dağınıklığı ve teknik kaygıyı tasarımla ortadan kaldıran yarı manuel; “geri bildirim zengin” bir espresso makinesi.,Sympress,"A semi-manual; ""feedback-rich"" espresso machine designed to preserve the tactile joy of coffee making while engineering out the mess and technical anxiety.",Gemini; Vizcom,cover/0121.jpg,logbook/0121.pdf
122,Edvin Mert,Cincioğlu,4,KAIRO-Sürdürülebilir Outdoor Teknolojisi,Konseptim; doğaya zarar vermeden enerji üretebilen taşınabilir bir outdoor teknoloji sistemidir. İndüksiyon teknolojisi ve sürdürülebilir enerji kaynakları kullanarak hızlı kaynatma; yemek pişirme ve genel ısıtma sağlar. Basit arayüzü ve kullanıcı odaklı tasarımıyla trekking ve kamp aktivitelerinde güvenli ve pratik bir deneyim sunar.,KAIRO-Sustainable Outdoor Technology,My concept is a portable outdoor technology system that generates energy without harming the environment. By using induction technology and sustainable energy sources; it provides fast boiling; cooking; and general heating. With its simple interface and user-focused design; it offers a safe and practical experience for trekking and camping activities.,ChatGPT; Gemini; Vizcom,cover/0122.jpg,logbook/0122.pdf
123,Selin,Anzerlioğlu,4,Wellness Odaklı Yönlendirmeli Çay Demleme Sistemi,Bitki ve fonksiyonel çayların doğru miktar ve demleme koşullarıyla hazırlanmasını destekleyen; kullanıcıyı süreç boyunca yönlendiren yarı otomatik bir çay demleme sistemi.,Guided Wellness Tea Brewing System,A guided brewing system that supports controlled preparation of herbal tea blends; helping users maintain appropriate proportions and steeping conditions while staying involved in the brewing ritual.,ChatGPT; Gemini; Vizcom; WhiskAI; chracter.ai,cover/0123.jpg,logbook/0123.pdf
124,Şenel,Savaş,4,ZenTea-Ritüel Felsefesini Koruyan Pratik AI destekli Çay Hazırlama Makinası,Bitki çaylarının hazırlanmasını kolaylaştıran; su sıcaklığı; demleme süresi ve bitki oranlarını otomatik olarak ayarlayan AI destekli bir çay hazırlama makinesi. Sistem farklı wellness modlarıyla çay hazırlama deneyimini pratik ve ritüel odaklı hale getirir.,ZenTea – AI-Assisted Tea Preparation Machine Preserving the Ritual Philosophy,An AI-assisted tea preparation machine that automates water temperature; infusion time; and herbal ratios to simplify herbal tea brewing. The system offers wellness modes that make tea preparation both practical and ritual-oriented.,ChatGPT; Gemini; Vizcom,cover/0124.jpg,logbook/0124.pdf
125,Serhan,Bozdağ,4,Zamanı Yeniden Çerçeveleyen Sıcak İçecek Hazırlama Cihazı,Sıcak içecek hazırlama süresini aceleyle geçilen bir görevden; kullanıcının seçtiği tempoda işleyen kişisel bir demleme ritüeline dönüştüren tezgahüstü bir cihaz geliştirir. Cihaz; farklı hız modları; ritüel odaklı arayüz akışı ve duyusal geri bildirimler aracılığıyla kullanıcıya zamanını yeniden kurgulama imkânı sunar.,Reframing Time in Hot Beverage Preparation,This project proposes a countertop device that turns hot beverage preparation from a rushed task into a personal brewing ritual that follows the user’s preferred tempo. The device offers multiple speed modes; a ritual-oriented interface flow and sensory feedback; enabling users to reframe their perception of time during hot beverage preparation.,ChatGPT; Gemini; Vizcom; Perplexity; Manus AI,cover/0125.jpg,logbook/0125.pdf
126,Duru Su,Dolap,4,Tente,Tente; öğrenci stüdyoları ve ortak çalışma alanları gibi paylaşılan ortamlarda kullanılmak üzere tasarlanmış bir kahve makinesidir; kullanıcıların kahve hazırlarken kısa bir mola vermelerini sağlarken; bu kısa süre içerisinde aynı ortamda bulunan diğer kişilerle doğal bir sosyal etkileşim kurmalarını teşvik eder.,Canopy,Canopy is a coffee machine designed for shared environments such as student studios and co-working spaces; enabling users to take a short break while preparing coffee and encouraging natural social interaction with others in the same space during this brief pause.,ChatGPT; Gemini; Vizcom,cover/0126.jpg,logbook/0126.pdf
127,Tuana,Ildız,4,NOVA - Yapılandırılmış Mikro Ritüel İstasyonu,Bu proje; yoğun günlük rutinler içerisinde kaybolan küçük hazırlık ritüellerini yeniden yapılandırmayı amaçlayan modüler bir içecek hazırlama istasyonu önermektedir. Tasarım; kahve ve bitki çayı hazırlama süreçlerini tek bir kompakt sistem içinde birleştirirken kullanıcıya daha bilinçli ve kontrollü bir hazırlık deneyimi sunmayı hedefler. Sistem; reusable kapsüller ve değiştirilebilir demleme modülleri kullanarak hem sürdürülebilir bir yaklaşım sunar hem de mutfak tezgâhlarında oluşan cihaz karmaşasını azaltır. Böylece kullanıcı; içeceğini hazırlarken küçük ama anlamlı bir ritüel deneyimi yaşayabilir.,NOVA - Structured Micro-Ritual Station,This project proposes a modular beverage preparation station designed to reintroduce small daily preparation rituals within fast-paced routines. The system combines coffee and herbal tea preparation within a single compact appliance while encouraging a more mindful and structured interaction. Using reusable capsules and interchangeable brewing modules; the design supports sustainability while reducing appliance clutter commonly found in kitchen or coffee-corner environments. The result is a compact station that transforms everyday beverage preparation into a small but meaningful ritual.,ChatGPT; Gemini; Vizcom,cover/0127.jpg,logbook/0127.pdf
128,Yıldız,BüyükŞahin,4,Momento-Ritüel Odaklı Pour-Over Kahve Hazırlama Seti,Momento; kahve hazırlama sürecini sadece işlevsel bir işlem olmaktan çıkarıp kullanıcı için bir mikro-ritüele ve zihinsel geçiş anına dönüştüren bir pour-over setidir. Sistem; ritüel deneyimini korurken stresi azaltmak için otomasyon ile kullanıcı katılımını dengeler.,Momento;Ritual-Focused Pour-Over Coffee Preparation Set,Momento is a pour-over coffee set that transforms coffee preparation from a purely functional task into a micro-ritual and a mental transition moment for the user. The system balances user participation with subtle automation to preserve the ritual experience while reducing stress.,ChatGPT; Gemini; Vizcom,cover/0128.jpg,logbook/0128.pdf
129,Ayşe Zeynep,Hocaoğlu,4,Thea,Thea; sıcak içecek hazırlama sürecinde otomasyon ile kullanıcı katılımını dengelleyerek çay ve bitkisel infüzyonların hazırlanmasını günlük bir ritüele dönüştüren bir elektrikli demleme sistemidir.,Thea,Thea is an electric tea-brewing system that balances automation with user participation; transforming the preparation of tea and herbal infusions into a meaningful daily ritual.,ChatGPT; Gemini; Vizcom,cover/0129.jpg,logbook/0129.pdf
130,Zeynep,Yazıcı,4,Whiska Seramonik Maça Makinesi,Whiska; geleneksel matcha hazırlama ritüelini modern teknolojiyle birleştiren işletmelere özel bir matcha hazırlama makinesidir.,Whiska Ceremonial Matcha Machine,Whiska is a matcha preparation machine designed for businesses that combines the traditional matcha preparation ritual with modern technology.,ChatGPT; Gemini; Vizcom,cover/0130.jpg,logbook/0130.pdf
131,Zulal,Koç,4,Geleneksel Mate Kültürünü Modern Kullanım İçin Yeniden Yorumlamak,Bu tasarım; profesyonel sporcular tarafından sıkça tüketilen yerba mate çayının geleneksel ve zahmetli hazırlama sürecini makine tabanlı bir sistemle yeniden yorumlamaktadır. Günümüzün hızlı yaşam temposunda zaman kaybını azaltmayı ve ortak kullanım alanlarında hızlı ve pratik tüketim imkânı sağlamayı amaçlamaktadır.,Reinterpreting Traditional Mate Culture for Modern Use,This design reinterprets the traditional preparation of yerba mate; widely consumed by professional athletes; by transforming its lengthy and labor-intensive process into an efficient; machine-based system. It aims to eliminate time constraints in today’s fast-paced lifestyles while enabling quick and convenient consumption in shared environments.,ChatGPT; Gemini; Vizcom,cover/0131.jpg,logbook/0131.pdf
132,Can,Sözen,4,Kompakt Seyahat Su Isıtıcısı,Bu proje; geçici konaklama ortamlarında kullanılan ortak su ısıtıcılarının yarattığı hijyen ve güven sorunlarına çözüm olarak tasarlanmış kompakt bir kişisel su ısıtıcısı önerir. Tasarım; basit silindirik yapı; taşınabilir form ve kullanıcıya kontrol hissi veren açık mekanik bağlantılar üzerine odaklanır.,Compact Travel Kettle,This project proposes a compact personal kettle designed for temporary accommodation environments where shared appliances create hygiene concerns. The design focuses on a minimal cylindrical structure; portable form; and visible mechanical connections that provide a clearer and more controllable user interaction.,ChatGPT,cover/0132.jpg,logbook/0132.pdf
133,Deniz,Civan,4,CHAI-Zamanlanabilir Otomatik Çay Makinesi,Bu proje; çay hazırlama sürecini daha güvenli ve pratik hale getirmek için tasarlanmış akıllı bir çay makinesi önerir. Sistem; çayın belirli bir zamanda otomatik olarak hazırlanmasını sağlar ve kullanıcıların kaynar su ve buharla doğrudan etkileşimini azaltmayı amaçlar.,Smart Automatic Tea Maker,This project proposes a smart tea maker designed to simplify tea preparation while improving safety. The system allows tea to be brewed automatically at a scheduled time and reduces direct interaction with boiling water and steam.,ChatGPT; Gemini; Vizcom,cover/0133.jpg,logbook/0133.pdf
134,Irem,İşbırakmaz,4,Yönlendirilmiş ve Ritüel Odaklı Demleme Deneyimi,Sıcak içecek türlerine göre yönlendirme sağlayan arayüzü ile demleme sürecini daha bilinçli ve ritüel odaklı bir deneyime dönüştürmeyi amaçlar.,Guided and Ritual Brewing Experience,Through an interface that guides users according to different hot beverage types; the design aims to transform the brewing process into a more mindful and ritual-oriented experience.,ChatGPT; Gemini; Vizcom,cover/0134.jpg,logbook/0134.pdf
135,Ömer,Kılıç,4,PAUSA - GYM Bitkisel Çay,Bu proje; spor sonrası kullanıcıların kısa bir duraklama yaşayabileceği bir recovery tea ritüeli yaratmayı amaçlayan bir gym içi sosyal cooldown sistemidir. Tasarım; kullanıcıların bitkisel recovery çayını kendilerinin demleyip paylaşabilecekleri döner platformlu bir çay ısıtıcısı ve island oturma düzeni etrafında kurgulanmıştır. Sistem gym üyelik kartı ile entegre çalışarak kullanıcılara haftalık veya aylık recovery tea hakkı sunar.,PAUSA - GYM Recovery Tea,This project proposes a gym-based cooldown system that encourages users to slow down after workouts through a recovery tea ritual. The design centers around a rotating herbal tea brewer placed on a circular island table; allowing users to brew and pour their own tea. The system integrates with gym membership cards to provide weekly or monthly recovery tea access for members.,ChatGPT; Gemini; Vizcom,cover/0135.jpg,logbook/0135.pdf
136,Yaren,Tüysüz,4,Anlık ihtiyaç ile bilinçli ritüel arasında geçiş kurmak,Bu proje; kullanıcının o anki ihtiyacına göre kahve hazırlama sürecindeki katılım seviyesini ayarlayabildiği bir kahve makinesi sistemidir. Sistem; hızlı ve otomatik kullanım ile daha yavaş; bilinçli ve ritüel odaklı hazırlık arasında geçiş kurarak farklı kullanım senaryolarına uyum sağlar.,Bridging Instant Need and Conscious Ritual,This project proposes a coffee machine system that allows users to adjust their level of participation in the coffee preparation process according to their immediate needs. The system enables a transition between fast; automated use and a slower; more deliberate ritual-oriented preparation; adapting to different usage scenarios.,ChatGPT; Gemini; Vizcom,cover/0136.jpg,logbook/0136.pdf
137,Zeynep,Tel,4,ÖZÜM,"ÖZÜM; yurt ortamında yaşayan üniversite öğrencileri için tasarlanmış; kişisel bir ""yuva kurma ritüeli"" ve ortak kullanım servis modelidir. Proje; oryantasyon döneminde hediye edilen kişisel termosu ve ortak mutfaklardaki merkezi ısıtma istasyonunu birleştirerek; güvenli ve hijyenik bir içecek hazırlama deneyimi sunar. Sadece su kaynatmanın ötesinde; öğrencilerin paylaşımlı alanlarda aidiyet; özerklik ve duygusal bağ kurmalarını sağlayan kompakt bir sistemdir.",OZUM,"ÖZÜM is a personal ""nesting ritual"" and shared service model designed for university students living in dormitories. By combining personal thermoses provided during orientation with a central heating station in communal kitchens; the project offers a safe and hygienic beverage preparation experience. Beyond just boiling water; it is a compact system that empowers students to establish autonomy; belonging; and emotional grounding in shared environments.",ChatGPT; Gemini; Vizcom,cover/0137.jpg,logbook/0137.pdf`;

// Galeride gostermek istemedigin proje ID'lerini bu diziye ekle.
// Ornek: const hiddenProjectIds = [3, 15, 42];
const hiddenProjectIds = [2, 18, 20, 24, 25, 31, 34, 35, 40, 41, 64];

function parseProjectsCsv(csvText) {
    const lines = csvText
        .split(/\r?\n/)
        .map(line => line.trim())
        .filter(Boolean);

    if (lines.length < 2) return [];

    const headers = lines[0].split(',').map(h => h.trim());
    const getIndex = (key) => headers.indexOf(key);

    return lines.slice(1).map((line) => {
        const cols = line.split(',').map(col => col.trim());
        const year = Number(cols[getIndex('year')]) || 1;
        const firstName = cols[getIndex('first_name')] || '';
        const lastName = cols[getIndex('last_name')] || '';
        const titleTr = cols[getIndex('title_tr')] || '';
        const titleEn = cols[getIndex('title_en')] || '';
        const shortDescTr = cols[getIndex('short_desc_tr')] || '';
        const shortDescEn = cols[getIndex('short_desc_en')] || '';
        const toolsRaw = cols[getIndex('tools')] || '';
        const image = cols[getIndex('image')] || '';
        const pdf = cols[getIndex('pdf')] || '#';
        const idValue = Number(cols[getIndex('id')]) || 0;

        return {
            id: idValue,
            student: `${firstName} ${lastName}`.trim(),
            year: { tr: `${year}. Sınıf`, en: `Year ${year}` },
            title: { tr: titleTr, en: titleEn },
            short_desc: { tr: shortDescTr, en: shortDescEn },
            tools: toolsRaw ? toolsRaw.split(';').map(tool => tool.trim()).filter(Boolean) : [],
            image,
            pdf
        };
    });
}

const hiddenProjectIdSet = new Set(
    hiddenProjectIds
        .map((id) => Number(id))
        .filter((id) => Number.isInteger(id) && id > 0)
);

const projects = parseProjectsCsv(projectsCsv)
    .filter((project) => !hiddenProjectIdSet.has(project.id));
